//
// This file has been generated by ./.generate-index.sh
//
// It MUST be re-generated each time an API namespace (read file) is
// added or removed.
//
export { default as backups } from './backups'
export { default as jobs } from './jobs'
export { default as plugins } from './plugins'
export { default as remotes } from './remotes'
export { default as scheduling } from './scheduling'
