import type { XenApiNetwork, XenApiVif, XenApiVm } from '@/libs/xen-api/xen-api.types'
import {
  type BaseVifFormData,
  buildBaseVifPayload,
  useVifFormBaseValidation,
} from '@/modules/vif/form/use-vif-form-base'
import type { EditVifPayload } from '@/modules/vif/jobs/xen-api-vif-edit.job'
import { useNetworkStore } from '@/stores/xen-api/network.store'
import { useVifStore } from '@/stores/xen-api/vif.store'
import { mergeValidationConfigs, required } from '@core/packages/form-validation'
import { useValidatedForm } from '@core/packages/validated-form'
import { toComputed } from '@core/utils/to-computed.util'
import { computed, reactive, watch } from 'vue'

export type EditVifFormData = BaseVifFormData & {
  network: XenApiNetwork['$ref'] | undefined
  actualVif: XenApiVif['$ref']
}

export function useEditVifForm(rawVmRef: XenApiVm['$ref'], rawActualVifRef: XenApiVif['$ref']) {
  const { getByOpaqueRef: getVifByRef } = useVifStore().subscribe()
  const { records: networks } = useNetworkStore().subscribe()

  const actualVifRef = toComputed(rawActualVifRef)

  const actualVif = computed(() => getVifByRef(actualVifRef.value))

  const formData = reactive<EditVifFormData>({
    network: undefined,
    actualVif: actualVifRef.value,
    mac: '',
    rateLimit: undefined,
    allowedIps: '',
    txChecksumming: true,
  })

  const fillFormFromVif = (vif?: XenApiVif) => {
    formData.actualVif = actualVifRef.value

    if (vif === undefined) {
      formData.network = undefined
      formData.mac = ''
      formData.rateLimit = undefined
      formData.allowedIps = ''
      formData.txChecksumming = true
      return
    }

    formData.network = vif.network
    formData.mac = vif.MAC_autogenerated ? '' : vif.MAC
    formData.rateLimit = vif.qos_algorithm_type === 'ratelimit' ? Number(vif.qos_algorithm_params.kbps) : undefined
    formData.allowedIps = [...vif.ipv4_allowed, ...vif.ipv6_allowed].join(';')
    formData.txChecksumming = vif.other_config['ethtool-tx'] === 'true'
  }

  const { useField, useFormSelect, useSelect, validate } = useValidatedForm(
    formData,
    mergeValidationConfigs<BaseVifFormData, EditVifFormData>(useVifFormBaseValidation(), {
      errors: {
        onSubmit: () => ({
          network: { required },
        }),
      },
    })
  )

  watch(
    actualVif,
    vif => {
      fillFormFromVif(vif)
    },
    { immediate: true }
  )

  const { id: networkSelectId } = useFormSelect('network', networks, {
    searchable: true,
    required: true,
    option: {
      id: '$ref',
      label: 'name_label',
      value: '$ref',
    },
  })

  async function validateAndBuildPayload(): Promise<EditVifPayload | undefined> {
    const isValid = await validate()

    if (!isValid || formData.network === undefined) {
      return undefined
    }

    return {
      vmRef: rawVmRef,
      networkRef: formData.network,
      actualVifRef: formData.actualVif as EditVifPayload['actualVifRef'],
      ...buildBaseVifPayload(formData),
    }
  }

  return {
    networkSelectBindings: useSelect(networkSelectId),
    macInputBindings: useField('mac'),
    rateLimitInputBindings: useField('rateLimit'),
    allowedIpsTextareaBindings: useField('allowedIps'),
    txChecksummingCheckboxBindings: useField('txChecksumming'),
    validateAndBuildPayload,
  }
}
