language: node_js
node_js:
  #- stable # disable for now due to an issue of indirect dep upath with Node 9
  - 8
  - 6

# Use containers.
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
addons:
  apt:
    packages:
      - qemu-utils
      - blktap-utils
      - vmdk-stream-converter

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true

script:
  - if [ "$TRAVIS_BRANCH" != "master" ]; then yarn run test; fi
  - if [ "$TRAVIS_BRANCH" != "master" ]; then yarn run test-integration; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then yarn run test-branch; fi
