import test from 'node:test'
import { strict as assert } from 'node:assert'

import tmp from 'tmp'
import fs from 'fs-extra'
import * as uuid from 'uuid'
import { getHandler } from '@xen-orchestra/fs'
import { pFromCallback, Disposable } from 'promise-toolbox'
import { RandomAccessDisk } from '@xen-orchestra/disk-transform'
import { openVhd } from 'vhd-lib'
import { rimraf } from 'rimraf'

import { RemoteAdapter } from './RemoteAdapter.mjs'

const { beforeEach, afterEach, describe } = test

// RemoteAdapter is now a facade over @xen-orchestra/backup-archive: the archive statics are
// deliberately lock-free and the adapter is what makes them safe to use concurrently. These
// tests cover what the facade adds, not what it delegates.

const BLOCK_SIZE = 2 * 1024 * 1024

let tempDir, handler, adapter
const vmUuid = 'test-vm-uuid'
const rootPath = `xo-vm-backups/${vmUuid}`
const cachePath = `${rootPath}/cache.json.gz`

beforeEach(async () => {
  tempDir = await pFromCallback(cb => tmp.dir(cb))
  handler = getHandler({ url: `file://${tempDir}` })
  await handler.sync()
  adapter = new RemoteAdapter(handler)
  await fs.mkdirp(`${tempDir}/${rootPath}`)
})

afterEach(async () => {
  await rimraf(tempDir)
  await handler.forget()
})

async function writeMetadata(name, metadata = {}) {
  const path = `${rootPath}/${name}.json`
  await handler.outputFile(
    path,
    JSON.stringify({ mode: 'delta', vm: { uuid: vmUuid, is_a_template: false }, timestamp: 1, ...metadata })
  )
  return path
}

// the cache is regenerated by a detached action
async function waitForCache() {
  for (let i = 0; i < 100 && !(await fs.pathExists(`${tempDir}/${cachePath}`)); i++) {
    await new Promise(resolve => setTimeout(resolve, 10))
  }
  assert.equal(await fs.pathExists(`${tempDir}/${cachePath}`), true)
}

// records the highest number of overlapping `handler.list` calls
function watchConcurrentLists() {
  const original = handler.list.bind(handler)
  const state = { running: 0, max: 0, calls: 0 }
  handler.list = async (...args) => {
    state.calls++
    state.running++
    state.max = Math.max(state.max, state.running)
    try {
      return await original(...args)
    } finally {
      state.running--
    }
  }
  return state
}

describe('cache locking', () => {
  test('concurrent updates of the same cache do not lose any entry', async () => {
    await adapter._writeCache(cachePath, {})

    const entries = Array.from({ length: 20 }, (_, i) => `backup-${i}.json`)
    await Promise.all(
      entries.map(entry =>
        adapter._updateCache(cachePath, cache => {
          cache[entry] = { _filename: entry }
        })
      )
    )

    // an unlocked read-modify-write would keep only the last writer
    assert.deepEqual(Object.keys(await adapter._readCache(cachePath)).sort(), [...entries].sort())
  })

  test('concurrent listVmBackups do not regenerate the cache in parallel', async () => {
    await writeMetadata('20240102T030405Z')
    await writeMetadata('20240102T030406Z')

    const lists = watchConcurrentLists()
    const results = await Promise.all(Array.from({ length: 10 }, () => adapter.listVmBackups(vmUuid)))

    // the directory may be scanned more than once (the cache is written by a detached
    // action) but never by two concurrent regenerations
    assert.equal(lists.max, 1)
    for (const backups of results) {
      assert.equal(backups.length, 2)
    }
  })
})

describe('writeVmBackupMetadata', () => {
  test('adds the backup to the cache used by listVmBackups', async () => {
    await writeMetadata('20240102T030405Z')
    assert.equal((await adapter.listVmBackups(vmUuid)).length, 1)
    await waitForCache()

    const timestamp = Date.UTC(2024, 0, 2, 3, 4, 6)
    const path = await adapter.writeVmBackupMetadata(vmUuid, {
      mode: 'delta',
      vm: { uuid: vmUuid, is_a_template: false },
      timestamp,
    })

    assert.equal(path, `/${rootPath}/20240102T030406Z.json`)
    const backups = await adapter.listVmBackups(vmUuid)
    assert.equal(backups.length, 2)
    assert.ok(
      backups.some(backup => backup._filename === path),
      'the written backup is listed from the cache'
    )
  })
})

// the smallest disk `writeVhd` can consume
class MockDisk extends RandomAccessDisk {
  #blockIndexes

  constructor(blockIndexes) {
    super()
    this.#blockIndexes = blockIndexes
  }

  async init() {}
  async close() {}

  getVirtualSize() {
    return (Math.max(...this.#blockIndexes) + 1) * BLOCK_SIZE
  }

  getBlockSize() {
    return BLOCK_SIZE
  }

  isDifferencing() {
    return false
  }

  getBlockIndexes() {
    return this.#blockIndexes
  }

  hasBlock(index) {
    return this.#blockIndexes.includes(index)
  }

  async readBlock(index) {
    return { index, data: Buffer.alloc(BLOCK_SIZE, index) }
  }
}

describe('writeVhd', () => {
  test('reports the streamed size of a VHD file', async () => {
    const path = `${rootPath}/vdis/job/vdi/target.vhd`
    const validated = []

    const size = await adapter.writeVhd(path, new MockDisk([0, 1]), {
      validator: async validatedPath => validated.push(validatedPath),
    })

    // the size is accounted by the adapter, around the injected output stream
    assert.equal(size, (await fs.stat(`${tempDir}/${path}`)).size)
    // the handler validates the temporary file it streams to, then writeVhd validates the
    // final path
    assert.equal(validated.at(-1), path)

    await Disposable.use(openVhd(handler, path), async vhd => {
      await vhd.readBlockAllocationTable()
      assert.equal((await vhd.readBlock(1)).data.length, BLOCK_SIZE)
    })
  })

  test('writes a VHD directory and accepts it as a mergeable parent', async () => {
    const directoryHandler = getHandler({ url: `file://${tempDir}`, useVhdDirectory: true })
    await directoryHandler.sync()
    try {
      const directoryAdapter = new RemoteAdapter(directoryHandler, { vhdDirectoryCompression: 'brotli' })
      const path = `${rootPath}/vdis/job/vdi/target.alias.vhd`

      const size = await directoryAdapter.writeVhd(path, new MockDisk([0, 1]))
      assert.ok(size > 0)

      const footerUuid = await Disposable.use(openVhd(directoryHandler, path), vhd => vhd.footer.uuid)
      assert.equal(await directoryAdapter.isMergeableParent(footerUuid, path), true)
      // a VHD created from another parent must not be merged into this chain
      assert.equal(await directoryAdapter.isMergeableParent(uuid.v1({}, Buffer.alloc(16)), path), false)
    } finally {
      await directoryHandler.forget()
    }
  })
})
