/**
 * Represents an opaque reference in the format `OpaqueRef:...`.
 * @typedef {`OpaqueRef:${string}`} OpaqueRef
 */

/**
 * @typedef {Object} VBD
 * @property {OpaqueRef} VDI
 * @property {OpaqueRef} VM
 * @property {string[]} allowed_operations
 * @property {boolean} bootable
 * @property {Object} current_operations
 * @property {boolean} currently_attached
 * @property {"xvda" | string} device
 * @property {boolean} empty
 * @property {OpaqueRef} metrics
 * @property {"RW" | "RO" | string} mode
 * @property {Object} other_config
 * @property {Object} qos_algorithm_params
 * @property {string} qos_algorithm_type
 * @property {string[]} qos_supported_algorithms
 * @property {Object} runtime_properties
 * @property {number} status_code
 * @property {string} status_detail
 * @property {boolean} storage_lock
 * @property {"Disk" | string} type
 * @property {boolean} unpluggable
 * @property {"0" | string} userdevice
 * @property {string} uuid
 */

/**
 * @typedef {Object} VDI
 * @property {string} $SR$uuid
 * @property {string} $snapshot_of$uuid
 * @property {OpaqueRef} SR
 * @property {OpaqueRef[]} VBDs
 * @property {boolean} allow_caching
 * @property {boolean} allowed_operations
 * @property {boolean} cbt_enabled
 * @property {string[]} crash_dumps
 * @property {Object} current_operations
 * @property {boolean} is_a_snapshot
 * @property {boolean} is_tools_iso
 * @property {string} location
 * @property {string} managed
 * @property {boolean} metadata_latest
 * @property {OpaqueRef} metadata_of_pool
 * @property {boolean} missing
 * @property {string} name_description
 * @property {string} name_label
 * @property {string} on_boot
 * @property {Object} other_config
 * @property {OpaqueRef} parent
 * @property {number} physical_utilisation
 * @property {boolean} read_only
 * @property {boolean} sharable
 * @property {{ 'vhd-parent': string }} sm_config
 * @property {OpaqueRef} snapshot_of
 * @property {string} snapshot_time
 * @property {Object[]} snapshots
 * @property {boolean} storage_lock
 * @property {string[]} tags
 * @property {string} type
 * @property {string} uuid
 * @property {number} virtual_size
 * @property {Object} xenstore_data
 */

/**
 * @typedef {Object.<OpaqueRef, VDI>} VDIs
 */

/**
 * @typedef {Record<OpaqueRef, VBD>} VBDs
 */

/**
 * @typedef {Record<OpaqueRef, string>} VHDs
 */

/**
* @typedef {Object} Metadata
* @property {Object.<OpaqueRef | string, boolean>} isVhdDifferencing
* @property {string} jobId
* @property {"delta" | "full"} mode
* @property {string} scheduleId
* @property {number} size
* @property {number} timestamp
 * @property {XenApiVdi } vbds
* @property {Record<OpaqueRef, VDI} vdis
* @property {"2.0.0" | string} version
* @property {VHDs} vhds
* @property {Object.<OpaqueRef, {
*   $network$VLAN: number,
*   $network$name_label: string,
*   $network$uuid: string,
*   MAC: string,
*   MAC_autogenerated: boolean,
*   MTU: number,
*   VM: OpaqueRef,
*   allowed_operations: string[],
*   current_operations: Object,
*   currently_attached: boolean,
*   device: "0" | string,
*   ipv6_addresses: string[],
*   ipv6_allowed: string[],
*   ipv6_configuration_mode: "None" | string,
*   ipv6_gateway: string,
*   locking_mode: "network_default" | string,
*   metrics: OpaqueRef,
*   network: OpaqueRef,
*   other_config: Object,
*   qos_algorithm_params: Object,
*   qos_algorithm_type: string,
*   qos_supported_algorithms: string[],
*   runtime_properties: Object,
*   status_code: number,
*   status_detail: string,
*   uuid: string
* }>} vifs
* @property {Object} vm
* @property {Object} vmSnapshot
* @property {Object[]} vtpms
* @property {string} [xva]
*/
