[xoConnection]
  url = ''
  email = ''
  password = ''

[servers]
  [servers.default]
    username = ''
    password = ''
    host = ''

[vms]
  default = ''
  vmToBackup = ''

[templates]
  default = ''

[srs]
  default = ''

[remotes]
  default = { name = '', url = '' }
  nfs = { name = '', url = '' }
  # smb = { name = '', url = '' }
