[xoConnection]
  url = ''
  email = ''
  password = ''

[pools]
  default = ''

[servers]
  [servers.default]
    username = ''
    password = ''
    host = ''

[vms]
  default = ''
  # vmToBackup = ''

[templates]
  default = ''
  templateWithoutDisks = ''

[srs]
  default = ''

[remotes]
  default = { name = '', url = '' }
  remote1 = { name = '', url = '' }
  # remote2 = { name = '', url = '' }
