import type { RouteRecordInfo, ParamValue } from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/dev/': RouteRecordInfo<'/dev/', '/dev', Record<never, never>, Record<never, never>, never>
    '/dev/colors': RouteRecordInfo<'/dev/colors', '/dev/colors', Record<never, never>, Record<never, never>, never>
    '/dev/icons/': RouteRecordInfo<'/dev/icons/', '/dev/icons', Record<never, never>, Record<never, never>, never>
    '/dev/icons/[name]': RouteRecordInfo<
      '/dev/icons/[name]',
      '/dev/icons/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      never
    >
    '/dev/token': RouteRecordInfo<'/dev/token', '/dev/token', Record<never, never>, Record<never, never>, never>
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/dev/index.vue': {
      routes: '/dev/'
      views: never
    }
    'src/pages/dev/colors.vue': {
      routes: '/dev/colors'
      views: never
    }
    'src/pages/dev/icons/index.vue': {
      routes: '/dev/icons/'
      views: never
    }
    'src/pages/dev/icons/[name].vue': {
      routes: '/dev/icons/[name]'
      views: never
    }
    'src/pages/dev/token.vue': {
      routes: '/dev/token'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info> ? Info['routes'] : keyof RouteNamedMap
}

export {}
