import type XenApi from '@/libs/xen-api/xen-api'
import type { RecordRef, XenApiNetwork, XenApiVif, XenApiVm } from '@/libs/xen-api/xen-api.types'
import type { MaybeArray } from '@core/types/utility.type'
import { toArray } from '@core/utils/to-array.utils'

export function createVifOperations(xenApi: XenApi) {
  type VifRefs = MaybeArray<XenApiVif['$ref']>

  type VmRef = XenApiVm['$ref']

  type NetworkRef = XenApiNetwork['$ref']

  type VifCreateParams = {
    vmRef: VmRef
    device?: string
    network: NetworkRef
    MAC?: string
    MTU?: number
    other_config?: Record<string, any>
    qos_algorithm_params?: Record<string, any>
    qos_algorithm_type?: string
  }

  async function createVif(vif: VifCreateParams) {
    let {
      vmRef,
      device,
      network,
      MAC = '',
      MTU,
      other_config = {},
      qos_algorithm_params = {},
      qos_algorithm_type = '',
    } = vif

    if (device === undefined) {
      const [allowedDevices = []] = await xenApi.vm.getAllowedVifDevices(vmRef)

      device = allowedDevices.shift()
    }

    if (MTU === undefined) {
      MTU = await xenApi.getField<number>('network', network, 'MTU')
    }

    const vifRecord = {
      device,
      VM: vmRef,
      network,
      MAC,
      MTU,
      other_config,
      qos_algorithm_params,
      qos_algorithm_type,
    }

    return await xenApi.call('VIF.create', [vifRecord])
  }

  return {
    create: (vifs: VifCreateParams[]) => Promise.all(toArray(vifs).map(createVif)),

    delete: (vifRefs: VifRefs) => Promise.all(toArray(vifRefs).map(vifRef => xenApi.call('VIF.destroy', [vifRef]))),

    /**
     * @warning if you change mac adresse, the vif is recreate. so id change and minimal interupt is waite
     * @returns {XenApiVif['$ref']} return id of vif. id change if mac adress is modified
     */
    edit: async (actualVif: XenApiVif, editedVif: VifCreateParams): Promise<RecordRef<'vif'>> => {
      const deepEqual = function (x: any, y: any) {
        if (x === y) {
          return true
        } else if (typeof x === 'object' && x != null && typeof y === 'object' && y != null) {
          if (Object.keys(x).length !== Object.keys(y).length) return false

          for (const prop in x) {
            if (Object.prototype.hasOwnProperty.call(y, prop)) {
              if (!deepEqual(x[prop], y[prop])) return false
            } else return false
          }

          return true
        } else {
          return false
        }
      }

      const nextMac = editedVif.MAC ?? actualVif.MAC

      if (actualVif.MAC !== nextMac) {
        const newVif = { ...actualVif, ...(editedVif as Partial<XenApiVif>), MAC: nextMac } as XenApiVif

        if (newVif.MAC && !newVif.MAC_autogenerated) {
          newVif.MAC_autogenerated = true
        }
        if (!newVif.MAC && newVif.MAC_autogenerated) {
          newVif.MAC_autogenerated = false
        }

        if (actualVif.currently_attached) {
          await xenApi.call('VIF.unplug_force', [actualVif.$ref])
        }

        await xenApi.call('VIF.destroy', [actualVif.$ref])

        const newVifRef = await createVif({ ...newVif, vmRef: newVif.VM })

        if (actualVif.currently_attached) {
          await xenApi.call('VIF.plug', [newVifRef])
        }

        return newVifRef as RecordRef<'vif'>
      }

      await Promise.allSettled(
        (Object.keys(editedVif) as (keyof VifCreateParams)[]).map(param => {
          const actualValue = actualVif[param as keyof XenApiVif]
          const value = editedVif[param]

          if (param === 'vmRef') {
            return true
          }

          if (param === 'qos_algorithm_type' && value !== actualValue) {
            return xenApi.call('VIF.set_qos_algorithm_type', [actualVif.$ref, value ?? ''])
          }

          if (param === 'network' && value !== actualValue) {
            return xenApi.call('VIF.move', [actualVif.$ref, value])
          }

          if (param === 'other_config') {
            const mergedOtherConfig = Object.assign({}, actualVif.other_config, value ?? {})

            if (!deepEqual(actualValue, mergedOtherConfig)) {
              return xenApi.call('VIF.set_other_config', [actualVif.$ref, mergedOtherConfig])
            }

            return true
          }

          if (param === 'qos_algorithm_params' && !deepEqual(actualValue, value)) {
            return xenApi.call('VIF.set_qos_algorithm_params', [actualVif.$ref, value ?? {}])
          }

          if (value !== actualValue) {
            return xenApi.call(`VIF.set_${String(param)}`, [actualVif.$ref, value])
          }

          return true
        })
      )
      return actualVif.$ref
    },
  }
}
