import test from 'node:test'
import { strict as assert } from 'node:assert'

import tmp from 'tmp'
import fs from 'fs-extra'
import { getHandler } from '@xen-orchestra/fs'
import { pFromCallback } from 'promise-toolbox'
import { rimraf } from 'rimraf'
/* eslint-disable n/no-missing-import */
import { VmBackupDirectory } from '../VmBackupDirectory.mjs'
import { formatFilenameDate } from '../filenameDate.mjs'
/* eslint-enable n/no-missing-import */

const { beforeEach, afterEach, describe } = test

let tempDir, handler
const vmUuid = 'test-vm-uuid'
const rootPath = `xo-vm-backups/${vmUuid}`
const cachePath = `${rootPath}/cache.json.gz`

beforeEach(async () => {
  tempDir = await pFromCallback(cb => tmp.dir(cb))
  handler = getHandler({ url: `file://${tempDir}` })
  await handler.sync()
  await fs.mkdirp(`${tempDir}/${rootPath}`)
})

afterEach(async () => {
  await rimraf(tempDir)
  await handler.forget()
})

// the paths of a listing are prepended with the normalized (absolute) directory
const listed = path => `/${path}`

// a metadata file must at least carry `vm` and `timestamp` to be usable
async function writeMetadata(path, metadata = {}) {
  const fullMetadata = {
    mode: 'delta',
    vm: { uuid: vmUuid, is_a_template: false },
    timestamp: 1704164645000,
    ...metadata,
  }
  await handler.outputFile(path, JSON.stringify(fullMetadata))
  return fullMetadata
}

// counts the calls to `handler.list` while `fn` runs
async function countListCalls(fn) {
  const original = handler.list.bind(handler)
  let count = 0
  handler.list = (...args) => {
    count++
    return original(...args)
  }
  try {
    return { result: await fn(), count }
  } finally {
    delete handler.list
  }
}

describe('writeVmBackupMetadata', () => {
  test('writes the metadata at a dated path and adds it to the cache', async () => {
    const timestamp = Date.UTC(2024, 0, 2, 3, 4, 5)
    const metadata = { mode: 'delta', vm: { uuid: vmUuid }, timestamp }
    const cacheUpdates = []

    const path = await VmBackupDirectory.writeVmBackupMetadata(handler, vmUuid, metadata, {
      updateCache: async (cachePath, fn) => {
        const cache = {}
        fn(cache)
        cacheUpdates.push({ cachePath, cache })
      },
    })

    assert.equal(path, `/${rootPath}/${formatFilenameDate(timestamp)}.json`)
    assert.deepEqual(JSON.parse(await handler.readFile(path)), metadata)

    assert.equal(cacheUpdates.length, 1)
    assert.equal(cacheUpdates[0].cachePath, cachePath)
    // `_filename` and `id` are required by the consumers of the cache
    assert.deepEqual(cacheUpdates[0].cache[path], { ...metadata, _filename: path, id: path })
  })
})

describe('readVmBackupMetadata', () => {
  test('reads back a written metadata', async () => {
    const path = `${rootPath}/20240102T030405Z.json`
    const written = await writeMetadata(path)

    assert.deepEqual(await VmBackupDirectory.readVmBackupMetadata(handler, path), {
      ...written,
      _filename: path,
      isImmutable: false,
    })
  })

  test('repairs booleans stored as integers by XenServer < 7.1', async () => {
    const path = `${rootPath}/20240102T030405Z.json`
    await writeMetadata(path, {
      vm: { uuid: vmUuid, is_a_template: 0, is_control_domain: 1 },
      // collections are indexed by opaque ref
      vbds: { 'OpaqueRef:1': { bootable: 1, empty: 0 }, 'OpaqueRef:2': { bootable: 0 } },
      // ... but some metadata fields hold a single object
      vifs: { currently_attached: 1, MAC_autogenerated: 0 },
    })

    const metadata = await VmBackupDirectory.readVmBackupMetadata(handler, path)
    assert.equal(metadata.vm.is_a_template, false)
    assert.equal(metadata.vm.is_control_domain, true)
    assert.deepEqual(metadata.vbds, {
      'OpaqueRef:1': { bootable: true, empty: false },
      'OpaqueRef:2': { bootable: false },
    })
    assert.deepEqual(metadata.vifs, { currently_attached: true, MAC_autogenerated: false })
  })

  test('leaves recent metadata untouched', async () => {
    const path = `${rootPath}/20240102T030405Z.json`
    // `vm.is_a_template` is already a boolean => no repair at all
    await writeMetadata(path, { vbds: { 'OpaqueRef:1': { bootable: 1 } } })

    const metadata = await VmBackupDirectory.readVmBackupMetadata(handler, path)
    assert.deepEqual(metadata.vbds, { 'OpaqueRef:1': { bootable: 1 } })
  })

  test('flags the metadata as immutable when the remote is immutable', async () => {
    const flags = []
    const immutableHandler = {
      _readFile: async () => '{}',
      readFile: async (path, { flag } = {}) => {
        flags.push(flag)
        if (flag === 'r+') {
          const error = new Error('EPERM')
          error.code = 'EPERM'
          throw error
        }
        return JSON.stringify({ mode: 'delta', vm: { uuid: vmUuid, is_a_template: false } })
      },
    }

    const metadata = await VmBackupDirectory.readVmBackupMetadata(immutableHandler, 'backup.json')
    assert.equal(metadata.isImmutable, true)
    assert.deepEqual(flags, ['r+', 'r'])
  })

  test('does not retry when the remote is not immutable', async () => {
    const notImmutableHandler = {
      _readFile: async () => {
        const error = new Error('ENOENT')
        error.code = 'ENOENT'
        throw error
      },
      readFile: async () => {
        const error = new Error('EPERM')
        error.code = 'EPERM'
        throw error
      },
    }

    await assert.rejects(VmBackupDirectory.readVmBackupMetadata(notImmutableHandler, 'backup.json'), { code: 'EPERM' })
  })
})

describe('getCacheableDataListVmBackups', () => {
  test('reads every metadata file of the directory, and only those', async () => {
    await writeMetadata(`${rootPath}/20240102T030405Z.json`)
    await writeMetadata(`${rootPath}/20240102T030406Z.json`)
    await handler.outputFile(`${rootPath}/vdis/job/vdi/disk.vhd`, 'not a metadata')
    await VmBackupDirectory.writeCache(handler, cachePath, {})

    const backups = await VmBackupDirectory.getCacheableDataListVmBackups(handler, rootPath)
    assert.deepEqual(Object.keys(backups).sort(), [
      listed(`${rootPath}/20240102T030405Z.json`),
      listed(`${rootPath}/20240102T030406Z.json`),
    ])
    // an id usable by importVmBackup is injected
    for (const [path, metadata] of Object.entries(backups)) {
      assert.equal(metadata.id, path)
      assert.equal(metadata._filename, path)
    }
  })

  test('skips unreadable metadata instead of failing', async () => {
    await writeMetadata(`${rootPath}/20240102T030405Z.json`)
    await handler.outputFile(`${rootPath}/20240102T030406Z.json`, 'not json')

    const backups = await VmBackupDirectory.getCacheableDataListVmBackups(handler, rootPath)
    assert.deepEqual(Object.keys(backups), [listed(`${rootPath}/20240102T030405Z.json`)])
  })

  test('returns undefined when the VM directory does not exist', async () => {
    assert.equal(await VmBackupDirectory.getCacheableDataListVmBackups(handler, 'xo-vm-backups/unknown-vm'), undefined)
  })
})

describe('readCacheListVmBackups', () => {
  test('uses the cache without reading the directory', async () => {
    await writeMetadata(`${rootPath}/20240102T030405Z.json`)
    await VmBackupDirectory.writeCache(handler, cachePath, { 'cached.json': { timestamp: 1 } })

    const { result, count } = await countListCalls(() => VmBackupDirectory.readCacheListVmBackups(handler, vmUuid))

    assert.deepEqual(result, { 'cached.json': { timestamp: 1 } })
    assert.equal(count, 0)
  })

  test('regenerates and writes the cache when it is missing', async () => {
    const path = `${rootPath}/20240102T030405Z.json`
    await writeMetadata(path)

    const backups = await VmBackupDirectory.readCacheListVmBackups(handler, vmUuid)
    assert.deepEqual(Object.keys(backups), [listed(path)])

    // the cache is written by a detached action
    for (let i = 0; i < 100 && !(await fs.pathExists(`${tempDir}/${cachePath}`)); i++) {
      await new Promise(resolve => setTimeout(resolve, 10))
    }
    assert.deepEqual(Object.keys(await VmBackupDirectory.readCache(handler, cachePath)), [listed(path)])
  })

  test('bypasses the cache on an immutable remote', async () => {
    const path = `${rootPath}/20240102T030405Z.json`
    await writeMetadata(path)
    // an immutable remote may not allow modifying the cache file
    handler.isImmutable = () => true

    const backups = await VmBackupDirectory.readCacheListVmBackups(handler, vmUuid)
    assert.deepEqual(Object.keys(backups), [listed(path)])
    assert.equal(await fs.pathExists(`${tempDir}/${cachePath}`), false)
  })
})

describe('listAllVms', () => {
  test('lists the VM directories, ignoring hidden and lock files', async () => {
    await fs.mkdirp(`${tempDir}/xo-vm-backups/other-vm`)
    await handler.outputFile('xo-vm-backups/.hidden', '')
    await handler.outputFile('xo-vm-backups/other-vm.lock', '')

    assert.deepEqual((await VmBackupDirectory.listAllVms(handler)).sort(), ['other-vm', vmUuid])
  })

  test('is empty on a remote without any VM backup', async () => {
    await rimraf(`${tempDir}/xo-vm-backups`)
    assert.deepEqual(await VmBackupDirectory.listAllVms(handler), [])
  })
})

describe('listAllVmBackups', () => {
  const listVmBackups = vmUuid =>
    VmBackupDirectory.listVmBackups(uuid => VmBackupDirectory.readCacheListVmBackups(handler, uuid), vmUuid)

  test('maps each VM to its backups and skips VMs without any', async () => {
    await writeMetadata(`${rootPath}/20240102T030405Z.json`, { timestamp: 2 })
    await writeMetadata(`${rootPath}/20240102T030406Z.json`, { timestamp: 1 })
    await writeMetadata(`xo-vm-backups/other-vm/20240102T030405Z.json`, { timestamp: 3 })
    // a VM directory without any metadata is not listed
    await fs.mkdirp(`${tempDir}/xo-vm-backups/empty-vm`)

    const backups = await VmBackupDirectory.listAllVmBackups(handler, listVmBackups)

    assert.deepEqual(Object.keys(backups).sort(), ['other-vm', vmUuid])
    assert.deepEqual(
      backups[vmUuid].map(({ timestamp }) => timestamp),
      [1, 2]
    )
  })

  test('getTotalVmBackupSize sums the size of every backup of every VM', async () => {
    await writeMetadata(`${rootPath}/20240102T030405Z.json`, { size: 1, onDisk: 10 })
    await writeMetadata(`${rootPath}/20240102T030406Z.json`, { size: 100 })
    await writeMetadata(`xo-vm-backups/other-vm/20240102T030405Z.json`, { onDisk: 1000 })

    assert.deepEqual(await VmBackupDirectory.getTotalVmBackupSize(handler, listVmBackups), { onDisk: 1110 })
  })
})
