# List of skipped methods
[blockedList]
'acl.get' = true
'acl.getCurrentPermissions' = true
'audit.checkIntegrity' = true
'audit.generateFingerprint' = true
'audit.getRecords' = true
'backupNg.getAllJobs' = true
'backupNg.getAllLogs' = true
'cloud.getResourceCatalog' = true
'cloudConfig.getAll' = true
'group.getAll' = true
'host.stats' = true
'ipPool.getAll' = true
'job.getAll' = true
'log.get' = true
'metadataBackup.getAllJobs' = true
'plugin.get' = true
'pool.listMissingPatches' = true
'proxy.getAll' = true
'remote.getAll' = true
'remote.getAllInfo' = true
'resourceSet.getAll' = true
'role.getAll' = true
'schedule.getAll' = true
'server.getAll' = true
'session.getUser' = true
'sr.getUnhealthyVdiChainsLength' = true
'sr.stats' = true
'system.getMethodsInfo' = true
'system.getServerTimezone' = true
'system.getServerVersion' = true
'user.getAll' = true
'vm.stats' = true
'xo.getAllObjects' = true
'xoa.supportTunnel.getState' = true
'xosan.checkSrCurrentState' = true
'xosan.getVolumeInfo' = true
