#!/usr/bin/env sh

# TODO: this generation should probably be automated and integrated
# into the build system.

set -e -u

cd "$(dirname "$(which "$0")")"

{
  printf %s '//
// This file has been generated by ./.generate-index.sh
//
// It MUST be re-generated each time an API namespace (read file) is
// added or removed.
//
'

  for f in *.js *.coffee
  do
    base=${f%.*}
    [ "$base" != index ] || continue

    printf '%s\n' "export * as $base from './$base'"
  done | sort
} > index.js
