//
// This file has been generated by ./.generate-index.sh
//
// It MUST be re-generated each time an API namespace (read file) is
// added or removed.
//
export * as acl from './acl'
export * as disk from './disk'
export * as docker from './docker'
export * as group from './group'
export * as host from './host'
export * as job from './job'
export * as message from './message'
export * as remote from './remote'
export * as pbd from './pbd'
export * as pif from './pif'
export * as pool from './pool'
export * as role from './role'
export * as schedule from './schedule'
export * as scheduler from './scheduler'
export * as server from './server'
export * as session from './session'
export * as sr from './sr'
export * as task from './task'
export * as test from './test'
export * as token from './token'
export * as user from './user'
export * as vbd from './vbd'
export * as vdi from './vdi'
export * as vif from './vif'
export * as vm from './vm'
export * as xo from './xo'
