import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

/*
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
};

*/

export default {
  docs: [
    {
      type: 'category',
      label: 'Xen Orchestra',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: 'xen_orchestra/intro',
      },
      items: [
        'xen_orchestra/intro',
        'xen_orchestra/releases',
        'xen_orchestra/supported_hosts',
        'xen_orchestra/installation',
        'xen_orchestra/configuration',
        'xen_orchestra/migrate_to_new_xoa',
        'xen_orchestra/updater',
        'xen_orchestra/architecture',
        'xen_orchestra/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Management',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: 'Management/manage',
      },
      items: [
        'Management/manage',
        'Management/manage_infrastructure',
        'Management/users',
        'Management/advanced',
        'Management/load_balancing',
        'Management/sdn_controller',
        'Management/xosan',
        'Management/xosanv2',
      ],
    },
     {
      type: 'category',
      label: 'Backups',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: 'Backup/intro_backup',
      },
      items: [
        'Backup/intro_backup',
        'Backup/backups',
        'Backup/proxy',
        'Backup/rolling_snapshots',
        'Backup/full_backups',
        'Backup/delta_backups',
        'Backup/disaster_recovery',
        'Backup/continuous_replication',
        'Backup/mirror_backup',
        'Backup/metadata_backup',
        'Backup/backup_reports',
        'Backup/backup_troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Support',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: 'Support/intro_support',
      },
      items: [
        'Support/intro_support',
        'Support/xoa',
        'Support/purchase',
        'Support/licenses',
        'Support/community',
      ],
    },
    {
      type: 'category',
      label: 'Project',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: 'Project/intro_project',
      },
      items: [
        'Project/intro_project',
        {
          type: 'link',
          label: 'Changelog',
          href: 'https://github.com/vatesfr/xen-orchestra/blob/master/CHANGELOG.md#changelog',
        },
        'Project/contributing',
        'Project/code_of_conduct',
        'Project/roadmap',
        'Project/glossary',
      ],
    },
  ],
};

//export default sidebars;
