# Vendor config: DO NOT TOUCH!
#
# See sample.config.toml to override.

# This secret string is used to authenticate clients to the API.
#
# It must be defined to a non-empty string for the proxy to run.
authenticationToken = ''

datadir = '/var/lib/xo-proxy/data'
resourceDebounce = '5m'

[api]
keepAliveInterval = 10e3

[backups]
snapshotNameLabelTpl = '[XO Backup {job.name}] {vm.name_label}'

[backups.defaultSettings]
bypassVdiChainsCheck = false
checkpointSnapshot = false
concurrency = 2
deleteFirst = false
exportRetention = 0
fullInterval = 0
offlineBackup = false
offlineSnapshot = false
reportWhen = 'failure'
snapshotRetention = 0
timeout = 0
vmTimeout = 0

# This is a work-around.
#
# See https://github.com/vatesfr/xen-orchestra/pull/4674
maxMergedDeltasPerRun = 2

# Each `http.listen.<name>` entry defines a specific listening configuration for
# the HTTP server.
#
# `<name>` can be freely choosen.
[http.listen.https]

# Generate self-signed certificate if missing
autoCert = true

cert = '/var/lib/xo-proxy/certificate.pem'
key = '/var/lib/xo-proxy/key.pem'
port = 443

[remoteOptions]
mountsDir = '/run/xo-proxy/mounts'

# timeout in milliseconds (set to 0 to disable)
timeout = 600e3

# see https:#github.com/vatesfr/xen-orchestra/issues/3419
# useSudo = false

[xapiOptions]
maxUncoalescedVdis = 1
watchEvents = ['network', 'PIF', 'pool', 'SR', 'task', 'VBD', 'VDI', 'VIF', 'VM']
