declare module '@novnc/novnc/lib/rfb'
declare module '@xen-orchestra/human-format'
declare module 'iterable-backoff'
declare module 'json-rpc-protocol'
declare module 'promise-toolbox'
declare module 'xen-api'
