export const DEFAULT_VIF = {
  class: 'VIF',
  snapshot: {
    allowed_operations: [],
    currently_attached: false,
    current_operations: {},
    ipv4_addresses: [],
    ipv4_allowed: [],
    ipv4_configuration_mode: 'None',
    ipv4_gateway: '',
    ipv6_addresses: [],
    ipv6_allowed: [],
    ipv6_configuration_mode: 'None',
    ipv6_gateway: '',
    locking_mode: 'network_default',
    MTU: 1500,
    metrics: 'OpaqueRef:NULL',
    other_config: {},
    qos_algorithm_params: {},
    qos_algorithm_type: '',
    qos_supported_algorithms: [],
    runtime_properties: {},
    status_code: 0,
    status_detail: '',
  },
}
