export const DEFAULT_VM = {
  class: 'VM',
  id: null,
  snapshot: {
    actions_after_crash: 'restart',
    actions_after_reboot: 'restart',
    actions_after_shutdown: 'destroy',
    affinity: 'Ref:53',
    allowed_operations: [],
    // appliance:'OpaqueRef:NULL',
    attached_PCIs: [],
    blobs: {},
    blocked_operations: {},
    children: [],
    consoles: [],
    crash_dumps: [],
    current_operations: {},
    domain_type: 'hvm',
    domarch: '',
    domid: -1,
    generation_id: '',
    guest_metrics: 'Ref:53',
    ha_always_run: false,
    ha_restart_priority: '',
    hardware_platform_version: 0,
    has_vendor_device: false,
    HVM_boot_params: {
      firmware: 'bios',
      order: 'dcn',
    },
    HVM_boot_policy: 'BIOS order',
    HVM_shadow_multiplier: 1,
    is_a_template: false,
    is_control_domain: false,
    is_default_template: false,
    is_snapshot_from_vmpp: false,
    is_vmss_snapshot: false,
    last_booted_record: '',
    last_boot_CPU_flags: {},
    memory_dynamic_max: 1,
    memory_dynamic_min: 1,
    memory_overhead: 11534336,
    memory_static_max: 1,
    memory_static_min: 1,
    memory_target: 0,
    metrics: 'OpaqueRef:NULL',
    name_label: 'from xva',
    NVRAM: {},
    name_description: ' from xva',
    order: 0,
    other_config: {
      base_template_name: 'Other install media',
      // mac_seed,
      'install-methods': 'cdrom',
    },
    parent: 'OpaqueRef:NULL',
    PCI_bus: '',
    platform: {
      timeoffset: 1,
      'device-model': 'qemu-upstream-compat',
      secureboot: 'false',
      hpet: 'true',
      nx: 'true',
      pae: 'true',
      apic: 'true',
      viridian: 'true',
      acpi: 1,
    },
    power_state: 'halted',
    // protection_policy:'OpaqueRef:NULL',
    PV_args: '',
    PV_bootloader_args: '',
    PV_bootloader: '',
    PV_kernel: '',
    PV_legacy_args: '',
    PV_ramdisk: '',
    recommendations: '',
    reference_label: 'other-install-media',
    requires_reboot: false,
    resident_on: 'Ref:53',
    // scheduled_to_be_resident_on:'OpaqueRef:NULL',
    shutdown_delay: 0,
    // snapshot_schedule: 'OpaqueRef:NULL',
    snapshot_info: {},
    snapshot_metadata: '',
    snapshot_of: 'OpaqueRef:NULL',
    snapshot_time: new Date(0),
    snapshots: [],
    start_delay: 0,
    suspend_VDI: 'OpaqueRef:NULL',
    suspend_SR: 'OpaqueRef:NULL',
    tags: [],
    transportable_snapshot_id: '',
    // uuid,
    user_version: 1,
    VBDs: [],
    VCPUs_at_startup: 1,
    VCPUs_max: 1,
    VCPUs_params: {},
    version: 0,
    VGPUs: [],
    VIFs: [],
    VTPMs: [],
    VUSBs: [],
    xenstore_data: {},
  },
}
