/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>, never>
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      never
    >
    '/host/[uuid]': RouteRecordInfo<
      '/host/[uuid]',
      '/host/:uuid',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      | '/host/[uuid]/console'
      | '/host/[uuid]/dashboard'
      | '/host/[uuid]/network'
      | '/host/[uuid]/system'
      | '/host/[uuid]/tasks'
      | '/host/[uuid]/vms'
    >
    '/host/[uuid]/console': RouteRecordInfo<
      '/host/[uuid]/console',
      '/host/:uuid/console',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      never
    >
    '/host/[uuid]/dashboard': RouteRecordInfo<
      '/host/[uuid]/dashboard',
      '/host/:uuid/dashboard',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      never
    >
    '/host/[uuid]/network': RouteRecordInfo<
      '/host/[uuid]/network',
      '/host/:uuid/network',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      never
    >
    '/host/[uuid]/system': RouteRecordInfo<
      '/host/[uuid]/system',
      '/host/:uuid/system',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      never
    >
    '/host/[uuid]/tasks': RouteRecordInfo<
      '/host/[uuid]/tasks',
      '/host/:uuid/tasks',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      never
    >
    '/host/[uuid]/vms': RouteRecordInfo<
      '/host/[uuid]/vms',
      '/host/:uuid/vms',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      never
    >
    '/object-not-found': RouteRecordInfo<
      '/object-not-found',
      '/object-not-found',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/pool/[uuid]': RouteRecordInfo<
      '/pool/[uuid]',
      '/pool/:uuid',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      | '/pool/[uuid]/alarms'
      | '/pool/[uuid]/dashboard'
      | '/pool/[uuid]/hosts'
      | '/pool/[uuid]/network'
      | '/pool/[uuid]/stats'
      | '/pool/[uuid]/storage'
      | '/pool/[uuid]/system'
      | '/pool/[uuid]/tasks'
      | '/pool/[uuid]/vms'
    >
    '/pool/[uuid]/alarms': RouteRecordInfo<
      '/pool/[uuid]/alarms',
      '/pool/:uuid/alarms',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      never
    >
    '/pool/[uuid]/dashboard': RouteRecordInfo<
      '/pool/[uuid]/dashboard',
      '/pool/:uuid/dashboard',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      never
    >
    '/pool/[uuid]/hosts': RouteRecordInfo<
      '/pool/[uuid]/hosts',
      '/pool/:uuid/hosts',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      never
    >
    '/pool/[uuid]/network': RouteRecordInfo<
      '/pool/[uuid]/network',
      '/pool/:uuid/network',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      never
    >
    '/pool/[uuid]/stats': RouteRecordInfo<
      '/pool/[uuid]/stats',
      '/pool/:uuid/stats',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      never
    >
    '/pool/[uuid]/storage': RouteRecordInfo<
      '/pool/[uuid]/storage',
      '/pool/:uuid/storage',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      never
    >
    '/pool/[uuid]/system': RouteRecordInfo<
      '/pool/[uuid]/system',
      '/pool/:uuid/system',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      never
    >
    '/pool/[uuid]/tasks': RouteRecordInfo<
      '/pool/[uuid]/tasks',
      '/pool/:uuid/tasks',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      never
    >
    '/pool/[uuid]/vms': RouteRecordInfo<
      '/pool/[uuid]/vms',
      '/pool/:uuid/vms',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      never
    >
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>, never>
    '/story/': RouteRecordInfo<'/story/', '/story', Record<never, never>, Record<never, never>, never>
    '/story/form/form-byte-size': RouteRecordInfo<
      '/story/form/form-byte-size',
      '/story/form/form-byte-size',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/form/form-input': RouteRecordInfo<
      '/story/form/form-input',
      '/story/form/form-input',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/form/form-section': RouteRecordInfo<
      '/story/form/form-section',
      '/story/form/form-section',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/linear-chart': RouteRecordInfo<
      '/story/linear-chart',
      '/story/linear-chart',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/power-state-icon': RouteRecordInfo<
      '/story/power-state-icon',
      '/story/power-state-icon',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/progress-circle': RouteRecordInfo<
      '/story/progress-circle',
      '/story/progress-circle',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/story-example': RouteRecordInfo<
      '/story/story-example',
      '/story/story-example',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/ui-badge': RouteRecordInfo<
      '/story/ui-badge',
      '/story/ui-badge',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/ui-filter': RouteRecordInfo<
      '/story/ui-filter',
      '/story/ui-filter',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/banner/vts-banner': RouteRecordInfo<
      '/story/web-core/banner/vts-banner',
      '/story/web-core/banner/vts-banner',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/button-group/vts-button-group': RouteRecordInfo<
      '/story/web-core/button-group/vts-button-group',
      '/story/web-core/button-group/vts-button-group',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/card/vts-card-row-key-value': RouteRecordInfo<
      '/story/web-core/card/vts-card-row-key-value',
      '/story/web-core/card/vts-card-row-key-value',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/cell-object/vts-cell-object': RouteRecordInfo<
      '/story/web-core/cell-object/vts-cell-object',
      '/story/web-core/cell-object/vts-cell-object',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/cell-text/vts-cell-text': RouteRecordInfo<
      '/story/web-core/cell-text/vts-cell-text',
      '/story/web-core/cell-text/vts-cell-text',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/code-snippet/vts-code-snippet': RouteRecordInfo<
      '/story/web-core/code-snippet/vts-code-snippet',
      '/story/web-core/code-snippet/vts-code-snippet',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/columns/vts-columns': RouteRecordInfo<
      '/story/web-core/columns/vts-columns',
      '/story/web-core/columns/vts-columns',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/copy-button/vts-copy-button': RouteRecordInfo<
      '/story/web-core/copy-button/vts-copy-button',
      '/story/web-core/copy-button/vts-copy-button',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/donut-chart-with-legend/vts-donut-chart-with-legend': RouteRecordInfo<
      '/story/web-core/donut-chart-with-legend/vts-donut-chart-with-legend',
      '/story/web-core/donut-chart-with-legend/vts-donut-chart-with-legend',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/dropdown-title/vts-dropdown-title': RouteRecordInfo<
      '/story/web-core/dropdown-title/vts-dropdown-title',
      '/story/web-core/dropdown-title/vts-dropdown-title',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/input-wrapper/vts-input-wrapper': RouteRecordInfo<
      '/story/web-core/input-wrapper/vts-input-wrapper',
      '/story/web-core/input-wrapper/vts-input-wrapper',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/legend-group/vts-legend-group': RouteRecordInfo<
      '/story/web-core/legend-group/vts-legend-group',
      '/story/web-core/legend-group/vts-legend-group',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/object-icon/vts-object-icon': RouteRecordInfo<
      '/story/web-core/object-icon/vts-object-icon',
      '/story/web-core/object-icon/vts-object-icon',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/resources/vts-resource': RouteRecordInfo<
      '/story/web-core/resources/vts-resource',
      '/story/web-core/resources/vts-resource',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/resources/vts-resources': RouteRecordInfo<
      '/story/web-core/resources/vts-resources',
      '/story/web-core/resources/vts-resources',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/select/vts-select': RouteRecordInfo<
      '/story/web-core/select/vts-select',
      '/story/web-core/select/vts-select',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/stacked-bar-with-legend/vts-stacked-bar-with-legend': RouteRecordInfo<
      '/story/web-core/stacked-bar-with-legend/vts-stacked-bar-with-legend',
      '/story/web-core/stacked-bar-with-legend/vts-stacked-bar-with-legend',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/state-hero/vts-state-hero': RouteRecordInfo<
      '/story/web-core/state-hero/vts-state-hero',
      '/story/web-core/state-hero/vts-state-hero',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/status/vts-status': RouteRecordInfo<
      '/story/web-core/status/vts-status',
      '/story/web-core/status/vts-status',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/tab/router-tab': RouteRecordInfo<
      '/story/web-core/tab/router-tab',
      '/story/web-core/tab/router-tab',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/tab/tab-item': RouteRecordInfo<
      '/story/web-core/tab/tab-item',
      '/story/web-core/tab/tab-item',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/tab/tab-list': RouteRecordInfo<
      '/story/web-core/tab/tab-list',
      '/story/web-core/tab/tab-list',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/tree/vts-tree-item': RouteRecordInfo<
      '/story/web-core/tree/vts-tree-item',
      '/story/web-core/tree/vts-tree-item',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/tree/vts-tree-item-error': RouteRecordInfo<
      '/story/web-core/tree/vts-tree-item-error',
      '/story/web-core/tree/vts-tree-item-error',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/tree/vts-tree-list': RouteRecordInfo<
      '/story/web-core/tree/vts-tree-list',
      '/story/web-core/tree/vts-tree-list',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/tree/vts-tree-loading-item': RouteRecordInfo<
      '/story/web-core/tree/vts-tree-loading-item',
      '/story/web-core/tree/vts-tree-loading-item',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/account-menu-button/ui-account-menu-button': RouteRecordInfo<
      '/story/web-core/ui/account-menu-button/ui-account-menu-button',
      '/story/web-core/ui/account-menu-button/ui-account-menu-button',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/actions-title/ui-actions-title': RouteRecordInfo<
      '/story/web-core/ui/actions-title/ui-actions-title',
      '/story/web-core/ui/actions-title/ui-actions-title',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/alarm-item/ui-alarm-item': RouteRecordInfo<
      '/story/web-core/ui/alarm-item/ui-alarm-item',
      '/story/web-core/ui/alarm-item/ui-alarm-item',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/alarm-list/ui-alarm-list': RouteRecordInfo<
      '/story/web-core/ui/alarm-list/ui-alarm-list',
      '/story/web-core/ui/alarm-list/ui-alarm-list',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/alert/ui-alert': RouteRecordInfo<
      '/story/web-core/ui/alert/ui-alert',
      '/story/web-core/ui/alert/ui-alert',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/breadcrumb/ui-breadcrumb': RouteRecordInfo<
      '/story/web-core/ui/breadcrumb/ui-breadcrumb',
      '/story/web-core/ui/breadcrumb/ui-breadcrumb',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/button/ui-button': RouteRecordInfo<
      '/story/web-core/ui/button/ui-button',
      '/story/web-core/ui/button/ui-button',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/button-icon/ui-button-icon': RouteRecordInfo<
      '/story/web-core/ui/button-icon/ui-button-icon',
      '/story/web-core/ui/button-icon/ui-button-icon',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/card/ui-card': RouteRecordInfo<
      '/story/web-core/ui/card/ui-card',
      '/story/web-core/ui/card/ui-card',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/card/ui-card-subtitle': RouteRecordInfo<
      '/story/web-core/ui/card/ui-card-subtitle',
      '/story/web-core/ui/card/ui-card-subtitle',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/card/ui-card-title': RouteRecordInfo<
      '/story/web-core/ui/card/ui-card-title',
      '/story/web-core/ui/card/ui-card-title',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/card-numbers/ui-card-numbers': RouteRecordInfo<
      '/story/web-core/ui/card-numbers/ui-card-numbers',
      '/story/web-core/ui/card-numbers/ui-card-numbers',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/character-limit/ui-character-limit': RouteRecordInfo<
      '/story/web-core/ui/character-limit/ui-character-limit',
      '/story/web-core/ui/character-limit/ui-character-limit',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/checkbox/ui-checkbox': RouteRecordInfo<
      '/story/web-core/ui/checkbox/ui-checkbox',
      '/story/web-core/ui/checkbox/ui-checkbox',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/checkbox-group/ui-checkbox-group': RouteRecordInfo<
      '/story/web-core/ui/checkbox-group/ui-checkbox-group',
      '/story/web-core/ui/checkbox-group/ui-checkbox-group',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/chip/ui-chip': RouteRecordInfo<
      '/story/web-core/ui/chip/ui-chip',
      '/story/web-core/ui/chip/ui-chip',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/circle-progress-bar/ui-circle-progress-bar': RouteRecordInfo<
      '/story/web-core/ui/circle-progress-bar/ui-circle-progress-bar',
      '/story/web-core/ui/circle-progress-bar/ui-circle-progress-bar',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/collapsible-list/ui-collapsible-list': RouteRecordInfo<
      '/story/web-core/ui/collapsible-list/ui-collapsible-list',
      '/story/web-core/ui/collapsible-list/ui-collapsible-list',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/counter/ui-counter': RouteRecordInfo<
      '/story/web-core/ui/counter/ui-counter',
      '/story/web-core/ui/counter/ui-counter',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/data-ruler/ui-data-ruler': RouteRecordInfo<
      '/story/web-core/ui/data-ruler/ui-data-ruler',
      '/story/web-core/ui/data-ruler/ui-data-ruler',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/donut-chart/ui-donut-chart': RouteRecordInfo<
      '/story/web-core/ui/donut-chart/ui-donut-chart',
      '/story/web-core/ui/donut-chart/ui-donut-chart',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/dropdown/ui-dropdown': RouteRecordInfo<
      '/story/web-core/ui/dropdown/ui-dropdown',
      '/story/web-core/ui/dropdown/ui-dropdown',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/dropdown/ui-dropdown-list': RouteRecordInfo<
      '/story/web-core/ui/dropdown/ui-dropdown-list',
      '/story/web-core/ui/dropdown/ui-dropdown-list',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/dropdown-button/ui-dropdown-button': RouteRecordInfo<
      '/story/web-core/ui/dropdown-button/ui-dropdown-button',
      '/story/web-core/ui/dropdown-button/ui-dropdown-button',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/head-bar/ui-head-bar': RouteRecordInfo<
      '/story/web-core/ui/head-bar/ui-head-bar',
      '/story/web-core/ui/head-bar/ui-head-bar',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/info/ui-info': RouteRecordInfo<
      '/story/web-core/ui/info/ui-info',
      '/story/web-core/ui/info/ui-info',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/input/ui-input': RouteRecordInfo<
      '/story/web-core/ui/input/ui-input',
      '/story/web-core/ui/input/ui-input',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/input/ui-textarea': RouteRecordInfo<
      '/story/web-core/ui/input/ui-textarea',
      '/story/web-core/ui/input/ui-textarea',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/label/ui-label': RouteRecordInfo<
      '/story/web-core/ui/label/ui-label',
      '/story/web-core/ui/label/ui-label',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/legend/ui-legend': RouteRecordInfo<
      '/story/web-core/ui/legend/ui-legend',
      '/story/web-core/ui/legend/ui-legend',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/legend/ui-legend-title': RouteRecordInfo<
      '/story/web-core/ui/legend/ui-legend-title',
      '/story/web-core/ui/legend/ui-legend-title',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/link/ui-link': RouteRecordInfo<
      '/story/web-core/ui/link/ui-link',
      '/story/web-core/ui/link/ui-link',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/log-entry-viewer/ui-log-entry-viewer': RouteRecordInfo<
      '/story/web-core/ui/log-entry-viewer/ui-log-entry-viewer',
      '/story/web-core/ui/log-entry-viewer/ui-log-entry-viewer',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/logo-text/ui-logo-text': RouteRecordInfo<
      '/story/web-core/ui/logo-text/ui-logo-text',
      '/story/web-core/ui/logo-text/ui-logo-text',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/object-link/ui-object-link': RouteRecordInfo<
      '/story/web-core/ui/object-link/ui-object-link',
      '/story/web-core/ui/object-link/ui-object-link',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/panel/ui-panel': RouteRecordInfo<
      '/story/web-core/ui/panel/ui-panel',
      '/story/web-core/ui/panel/ui-panel',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/progress-bar/ui-progress-bar': RouteRecordInfo<
      '/story/web-core/ui/progress-bar/ui-progress-bar',
      '/story/web-core/ui/progress-bar/ui-progress-bar',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/query-search-bar/ui-query-search-bar': RouteRecordInfo<
      '/story/web-core/ui/query-search-bar/ui-query-search-bar',
      '/story/web-core/ui/query-search-bar/ui-query-search-bar',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/radio-button/ui-radio-button': RouteRecordInfo<
      '/story/web-core/ui/radio-button/ui-radio-button',
      '/story/web-core/ui/radio-button/ui-radio-button',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/radio-button-group/ui-radio-button-group': RouteRecordInfo<
      '/story/web-core/ui/radio-button-group/ui-radio-button-group',
      '/story/web-core/ui/radio-button-group/ui-radio-button-group',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/rich-radio-button/ui-rich-radio-button': RouteRecordInfo<
      '/story/web-core/ui/rich-radio-button/ui-rich-radio-button',
      '/story/web-core/ui/rich-radio-button/ui-rich-radio-button',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/stacked-bar/ui-stacked-bar': RouteRecordInfo<
      '/story/web-core/ui/stacked-bar/ui-stacked-bar',
      '/story/web-core/ui/stacked-bar/ui-stacked-bar',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/stepper/ui-stepper': RouteRecordInfo<
      '/story/web-core/ui/stepper/ui-stepper',
      '/story/web-core/ui/stepper/ui-stepper',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/subtitle/ui-subtitle': RouteRecordInfo<
      '/story/web-core/ui/subtitle/ui-subtitle',
      '/story/web-core/ui/subtitle/ui-subtitle',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/table-actions/ui-table-actions': RouteRecordInfo<
      '/story/web-core/ui/table-actions/ui-table-actions',
      '/story/web-core/ui/table-actions/ui-table-actions',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/table-pagination/ui-table-pagination': RouteRecordInfo<
      '/story/web-core/ui/table-pagination/ui-table-pagination',
      '/story/web-core/ui/table-pagination/ui-table-pagination',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/tag/ui-tag': RouteRecordInfo<
      '/story/web-core/ui/tag/ui-tag',
      '/story/web-core/ui/tag/ui-tag',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/tag/ui-tags-list': RouteRecordInfo<
      '/story/web-core/ui/tag/ui-tags-list',
      '/story/web-core/ui/tag/ui-tags-list',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/task-item/ui-task-item': RouteRecordInfo<
      '/story/web-core/ui/task-item/ui-task-item',
      '/story/web-core/ui/task-item/ui-task-item',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/task-list/ui-task-list': RouteRecordInfo<
      '/story/web-core/ui/task-list/ui-task-list',
      '/story/web-core/ui/task-list/ui-task-list',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/title/ui-title': RouteRecordInfo<
      '/story/web-core/ui/title/ui-title',
      '/story/web-core/ui/title/ui-title',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/toaster/ui-toaster': RouteRecordInfo<
      '/story/web-core/ui/toaster/ui-toaster',
      '/story/web-core/ui/toaster/ui-toaster',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/toggle/ui-toggle': RouteRecordInfo<
      '/story/web-core/ui/toggle/ui-toggle',
      '/story/web-core/ui/toggle/ui-toggle',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/top-bottom-table/ui-top-bottom-table': RouteRecordInfo<
      '/story/web-core/ui/top-bottom-table/ui-top-bottom-table',
      '/story/web-core/ui/top-bottom-table/ui-top-bottom-table',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/tree-item-label/ui-tree-item-label': RouteRecordInfo<
      '/story/web-core/ui/tree-item-label/ui-tree-item-label',
      '/story/web-core/ui/tree-item-label/ui-tree-item-label',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/user-link/ui-user-link': RouteRecordInfo<
      '/story/web-core/ui/user-link/ui-user-link',
      '/story/web-core/ui/user-link/ui-user-link',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/story/web-core/ui/user-logo/user-logo': RouteRecordInfo<
      '/story/web-core/ui/user-logo/user-logo',
      '/story/web-core/ui/user-logo/user-logo',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/vm/[uuid]': RouteRecordInfo<
      '/vm/[uuid]',
      '/vm/:uuid',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      | '/vm/[uuid]/alarms'
      | '/vm/[uuid]/console'
      | '/vm/[uuid]/dashboard'
      | '/vm/[uuid]/network'
      | '/vm/[uuid]/stats'
      | '/vm/[uuid]/storage'
      | '/vm/[uuid]/system'
      | '/vm/[uuid]/tasks'
    >
    '/vm/[uuid]/alarms': RouteRecordInfo<
      '/vm/[uuid]/alarms',
      '/vm/:uuid/alarms',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      never
    >
    '/vm/[uuid]/console': RouteRecordInfo<
      '/vm/[uuid]/console',
      '/vm/:uuid/console',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      never
    >
    '/vm/[uuid]/dashboard': RouteRecordInfo<
      '/vm/[uuid]/dashboard',
      '/vm/:uuid/dashboard',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      never
    >
    '/vm/[uuid]/network': RouteRecordInfo<
      '/vm/[uuid]/network',
      '/vm/:uuid/network',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      never
    >
    '/vm/[uuid]/stats': RouteRecordInfo<
      '/vm/[uuid]/stats',
      '/vm/:uuid/stats',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      never
    >
    '/vm/[uuid]/storage': RouteRecordInfo<
      '/vm/[uuid]/storage',
      '/vm/:uuid/storage',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      never
    >
    '/vm/[uuid]/system': RouteRecordInfo<
      '/vm/[uuid]/system',
      '/vm/:uuid/system',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      never
    >
    '/vm/[uuid]/tasks': RouteRecordInfo<
      '/vm/[uuid]/tasks',
      '/vm/:uuid/tasks',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      never
    >
    '/vm/new': RouteRecordInfo<'/vm/new', '/vm/new', Record<never, never>, Record<never, never>, never>
    '/xoa-deploy': RouteRecordInfo<'/xoa-deploy', '/xoa-deploy', Record<never, never>, Record<never, never>, never>
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/[...path].vue': {
      routes: '/[...path]'
      views: never
    }
    'src/pages/host/[uuid].vue': {
      routes:
        | '/host/[uuid]'
        | '/host/[uuid]/console'
        | '/host/[uuid]/dashboard'
        | '/host/[uuid]/network'
        | '/host/[uuid]/system'
        | '/host/[uuid]/tasks'
        | '/host/[uuid]/vms'
      views: 'default'
    }
    'src/pages/host/[uuid]/console.vue': {
      routes: '/host/[uuid]/console'
      views: never
    }
    'src/pages/host/[uuid]/dashboard.vue': {
      routes: '/host/[uuid]/dashboard'
      views: never
    }
    'src/pages/host/[uuid]/network.vue': {
      routes: '/host/[uuid]/network'
      views: never
    }
    'src/pages/host/[uuid]/system.vue': {
      routes: '/host/[uuid]/system'
      views: never
    }
    'src/pages/host/[uuid]/tasks.vue': {
      routes: '/host/[uuid]/tasks'
      views: never
    }
    'src/pages/host/[uuid]/vms.vue': {
      routes: '/host/[uuid]/vms'
      views: never
    }
    'src/pages/object-not-found.vue': {
      routes: '/object-not-found'
      views: never
    }
    'src/pages/pool/[uuid].vue': {
      routes:
        | '/pool/[uuid]'
        | '/pool/[uuid]/alarms'
        | '/pool/[uuid]/dashboard'
        | '/pool/[uuid]/hosts'
        | '/pool/[uuid]/network'
        | '/pool/[uuid]/stats'
        | '/pool/[uuid]/storage'
        | '/pool/[uuid]/system'
        | '/pool/[uuid]/tasks'
        | '/pool/[uuid]/vms'
      views: 'default'
    }
    'src/pages/pool/[uuid]/alarms.vue': {
      routes: '/pool/[uuid]/alarms'
      views: never
    }
    'src/pages/pool/[uuid]/dashboard.vue': {
      routes: '/pool/[uuid]/dashboard'
      views: never
    }
    'src/pages/pool/[uuid]/hosts.vue': {
      routes: '/pool/[uuid]/hosts'
      views: never
    }
    'src/pages/pool/[uuid]/network.vue': {
      routes: '/pool/[uuid]/network'
      views: never
    }
    'src/pages/pool/[uuid]/stats.vue': {
      routes: '/pool/[uuid]/stats'
      views: never
    }
    'src/pages/pool/[uuid]/storage.vue': {
      routes: '/pool/[uuid]/storage'
      views: never
    }
    'src/pages/pool/[uuid]/system.vue': {
      routes: '/pool/[uuid]/system'
      views: never
    }
    'src/pages/pool/[uuid]/tasks.vue': {
      routes: '/pool/[uuid]/tasks'
      views: never
    }
    'src/pages/pool/[uuid]/vms.vue': {
      routes: '/pool/[uuid]/vms'
      views: never
    }
    'src/pages/settings.vue': {
      routes: '/settings'
      views: never
    }
    'src/stories/index.story.vue': {
      routes: '/story/'
      views: never
    }
    'src/stories/form/form-byte-size.story.vue': {
      routes: '/story/form/form-byte-size'
      views: never
    }
    'src/stories/form/form-input.story.vue': {
      routes: '/story/form/form-input'
      views: never
    }
    'src/stories/form/form-section.story.vue': {
      routes: '/story/form/form-section'
      views: never
    }
    'src/stories/linear-chart.story.vue': {
      routes: '/story/linear-chart'
      views: never
    }
    'src/stories/power-state-icon.story.vue': {
      routes: '/story/power-state-icon'
      views: never
    }
    'src/stories/progress-circle.story.vue': {
      routes: '/story/progress-circle'
      views: never
    }
    'src/stories/story-example.story.vue': {
      routes: '/story/story-example'
      views: never
    }
    'src/stories/ui-badge.story.vue': {
      routes: '/story/ui-badge'
      views: never
    }
    'src/stories/ui-filter.story.vue': {
      routes: '/story/ui-filter'
      views: never
    }
    'src/stories/web-core/banner/vts-banner.story.vue': {
      routes: '/story/web-core/banner/vts-banner'
      views: never
    }
    'src/stories/web-core/button-group/vts-button-group.story.vue': {
      routes: '/story/web-core/button-group/vts-button-group'
      views: never
    }
    'src/stories/web-core/card/vts-card-row-key-value.story.vue': {
      routes: '/story/web-core/card/vts-card-row-key-value'
      views: never
    }
    'src/stories/web-core/cell-object/vts-cell-object.story.vue': {
      routes: '/story/web-core/cell-object/vts-cell-object'
      views: never
    }
    'src/stories/web-core/cell-text/vts-cell-text.story.vue': {
      routes: '/story/web-core/cell-text/vts-cell-text'
      views: never
    }
    'src/stories/web-core/code-snippet/vts-code-snippet.story.vue': {
      routes: '/story/web-core/code-snippet/vts-code-snippet'
      views: never
    }
    'src/stories/web-core/columns/vts-columns.story.vue': {
      routes: '/story/web-core/columns/vts-columns'
      views: never
    }
    'src/stories/web-core/copy-button/vts-copy-button.story.vue': {
      routes: '/story/web-core/copy-button/vts-copy-button'
      views: never
    }
    'src/stories/web-core/donut-chart-with-legend/vts-donut-chart-with-legend.story.vue': {
      routes: '/story/web-core/donut-chart-with-legend/vts-donut-chart-with-legend'
      views: never
    }
    'src/stories/web-core/dropdown-title/vts-dropdown-title.story.vue': {
      routes: '/story/web-core/dropdown-title/vts-dropdown-title'
      views: never
    }
    'src/stories/web-core/input-wrapper/vts-input-wrapper.story.vue': {
      routes: '/story/web-core/input-wrapper/vts-input-wrapper'
      views: never
    }
    'src/stories/web-core/legend-group/vts-legend-group.story.vue': {
      routes: '/story/web-core/legend-group/vts-legend-group'
      views: never
    }
    'src/stories/web-core/object-icon/vts-object-icon.story.vue': {
      routes: '/story/web-core/object-icon/vts-object-icon'
      views: never
    }
    'src/stories/web-core/resources/vts-resource.story.vue': {
      routes: '/story/web-core/resources/vts-resource'
      views: never
    }
    'src/stories/web-core/resources/vts-resources.story.vue': {
      routes: '/story/web-core/resources/vts-resources'
      views: never
    }
    'src/stories/web-core/select/vts-select.story.vue': {
      routes: '/story/web-core/select/vts-select'
      views: never
    }
    'src/stories/web-core/stacked-bar-with-legend/vts-stacked-bar-with-legend.story.vue': {
      routes: '/story/web-core/stacked-bar-with-legend/vts-stacked-bar-with-legend'
      views: never
    }
    'src/stories/web-core/state-hero/vts-state-hero.story.vue': {
      routes: '/story/web-core/state-hero/vts-state-hero'
      views: never
    }
    'src/stories/web-core/status/vts-status.story.vue': {
      routes: '/story/web-core/status/vts-status'
      views: never
    }
    'src/stories/web-core/tab/router-tab.story.vue': {
      routes: '/story/web-core/tab/router-tab'
      views: never
    }
    'src/stories/web-core/tab/tab-item.story.vue': {
      routes: '/story/web-core/tab/tab-item'
      views: never
    }
    'src/stories/web-core/tab/tab-list.story.vue': {
      routes: '/story/web-core/tab/tab-list'
      views: never
    }
    'src/stories/web-core/tree/vts-tree-item.story.vue': {
      routes: '/story/web-core/tree/vts-tree-item'
      views: never
    }
    'src/stories/web-core/tree/vts-tree-item-error.story.vue': {
      routes: '/story/web-core/tree/vts-tree-item-error'
      views: never
    }
    'src/stories/web-core/tree/vts-tree-list.story.vue': {
      routes: '/story/web-core/tree/vts-tree-list'
      views: never
    }
    'src/stories/web-core/tree/vts-tree-loading-item.story.vue': {
      routes: '/story/web-core/tree/vts-tree-loading-item'
      views: never
    }
    'src/stories/web-core/ui/account-menu-button/ui-account-menu-button.story.vue': {
      routes: '/story/web-core/ui/account-menu-button/ui-account-menu-button'
      views: never
    }
    'src/stories/web-core/ui/actions-title/ui-actions-title.story.vue': {
      routes: '/story/web-core/ui/actions-title/ui-actions-title'
      views: never
    }
    'src/stories/web-core/ui/alarm-item/ui-alarm-item.story.vue': {
      routes: '/story/web-core/ui/alarm-item/ui-alarm-item'
      views: never
    }
    'src/stories/web-core/ui/alarm-list/ui-alarm-list.story.vue': {
      routes: '/story/web-core/ui/alarm-list/ui-alarm-list'
      views: never
    }
    'src/stories/web-core/ui/alert/ui-alert.story.vue': {
      routes: '/story/web-core/ui/alert/ui-alert'
      views: never
    }
    'src/stories/web-core/ui/breadcrumb/ui-breadcrumb.story.vue': {
      routes: '/story/web-core/ui/breadcrumb/ui-breadcrumb'
      views: never
    }
    'src/stories/web-core/ui/button/ui-button.story.vue': {
      routes: '/story/web-core/ui/button/ui-button'
      views: never
    }
    'src/stories/web-core/ui/button-icon/ui-button-icon.story.vue': {
      routes: '/story/web-core/ui/button-icon/ui-button-icon'
      views: never
    }
    'src/stories/web-core/ui/card/ui-card.story.vue': {
      routes: '/story/web-core/ui/card/ui-card'
      views: never
    }
    'src/stories/web-core/ui/card/ui-card-subtitle.story.vue': {
      routes: '/story/web-core/ui/card/ui-card-subtitle'
      views: never
    }
    'src/stories/web-core/ui/card/ui-card-title.story.vue': {
      routes: '/story/web-core/ui/card/ui-card-title'
      views: never
    }
    'src/stories/web-core/ui/card-numbers/ui-card-numbers.story.vue': {
      routes: '/story/web-core/ui/card-numbers/ui-card-numbers'
      views: never
    }
    'src/stories/web-core/ui/character-limit/ui-character-limit.story.vue': {
      routes: '/story/web-core/ui/character-limit/ui-character-limit'
      views: never
    }
    'src/stories/web-core/ui/checkbox/ui-checkbox.story.vue': {
      routes: '/story/web-core/ui/checkbox/ui-checkbox'
      views: never
    }
    'src/stories/web-core/ui/checkbox-group/ui-checkbox-group.story.vue': {
      routes: '/story/web-core/ui/checkbox-group/ui-checkbox-group'
      views: never
    }
    'src/stories/web-core/ui/chip/ui-chip.story.vue': {
      routes: '/story/web-core/ui/chip/ui-chip'
      views: never
    }
    'src/stories/web-core/ui/circle-progress-bar/ui-circle-progress-bar.story.vue': {
      routes: '/story/web-core/ui/circle-progress-bar/ui-circle-progress-bar'
      views: never
    }
    'src/stories/web-core/ui/collapsible-list/ui-collapsible-list.story.vue': {
      routes: '/story/web-core/ui/collapsible-list/ui-collapsible-list'
      views: never
    }
    'src/stories/web-core/ui/counter/ui-counter.story.vue': {
      routes: '/story/web-core/ui/counter/ui-counter'
      views: never
    }
    'src/stories/web-core/ui/data-ruler/ui-data-ruler.story.vue': {
      routes: '/story/web-core/ui/data-ruler/ui-data-ruler'
      views: never
    }
    'src/stories/web-core/ui/donut-chart/ui-donut-chart.story.vue': {
      routes: '/story/web-core/ui/donut-chart/ui-donut-chart'
      views: never
    }
    'src/stories/web-core/ui/dropdown/ui-dropdown.story.vue': {
      routes: '/story/web-core/ui/dropdown/ui-dropdown'
      views: never
    }
    'src/stories/web-core/ui/dropdown/ui-dropdown-list.story.vue': {
      routes: '/story/web-core/ui/dropdown/ui-dropdown-list'
      views: never
    }
    'src/stories/web-core/ui/dropdown-button/ui-dropdown-button.story.vue': {
      routes: '/story/web-core/ui/dropdown-button/ui-dropdown-button'
      views: never
    }
    'src/stories/web-core/ui/head-bar/ui-head-bar.story.vue': {
      routes: '/story/web-core/ui/head-bar/ui-head-bar'
      views: never
    }
    'src/stories/web-core/ui/info/ui-info.story.vue': {
      routes: '/story/web-core/ui/info/ui-info'
      views: never
    }
    'src/stories/web-core/ui/input/ui-input.story.vue': {
      routes: '/story/web-core/ui/input/ui-input'
      views: never
    }
    'src/stories/web-core/ui/input/ui-textarea.story.vue': {
      routes: '/story/web-core/ui/input/ui-textarea'
      views: never
    }
    'src/stories/web-core/ui/label/ui-label.story.vue': {
      routes: '/story/web-core/ui/label/ui-label'
      views: never
    }
    'src/stories/web-core/ui/legend/ui-legend.story.vue': {
      routes: '/story/web-core/ui/legend/ui-legend'
      views: never
    }
    'src/stories/web-core/ui/legend/ui-legend-title.story.vue': {
      routes: '/story/web-core/ui/legend/ui-legend-title'
      views: never
    }
    'src/stories/web-core/ui/link/ui-link.story.vue': {
      routes: '/story/web-core/ui/link/ui-link'
      views: never
    }
    'src/stories/web-core/ui/log-entry-viewer/ui-log-entry-viewer.story.vue': {
      routes: '/story/web-core/ui/log-entry-viewer/ui-log-entry-viewer'
      views: never
    }
    'src/stories/web-core/ui/logo-text/ui-logo-text.story.vue': {
      routes: '/story/web-core/ui/logo-text/ui-logo-text'
      views: never
    }
    'src/stories/web-core/ui/object-link/ui-object-link.story.vue': {
      routes: '/story/web-core/ui/object-link/ui-object-link'
      views: never
    }
    'src/stories/web-core/ui/panel/ui-panel.story.vue': {
      routes: '/story/web-core/ui/panel/ui-panel'
      views: never
    }
    'src/stories/web-core/ui/progress-bar/ui-progress-bar.story.vue': {
      routes: '/story/web-core/ui/progress-bar/ui-progress-bar'
      views: never
    }
    'src/stories/web-core/ui/query-search-bar/ui-query-search-bar.story.vue': {
      routes: '/story/web-core/ui/query-search-bar/ui-query-search-bar'
      views: never
    }
    'src/stories/web-core/ui/radio-button/ui-radio-button.story.vue': {
      routes: '/story/web-core/ui/radio-button/ui-radio-button'
      views: never
    }
    'src/stories/web-core/ui/radio-button-group/ui-radio-button-group.story.vue': {
      routes: '/story/web-core/ui/radio-button-group/ui-radio-button-group'
      views: never
    }
    'src/stories/web-core/ui/rich-radio-button/ui-rich-radio-button.story.vue': {
      routes: '/story/web-core/ui/rich-radio-button/ui-rich-radio-button'
      views: never
    }
    'src/stories/web-core/ui/stacked-bar/ui-stacked-bar.story.vue': {
      routes: '/story/web-core/ui/stacked-bar/ui-stacked-bar'
      views: never
    }
    'src/stories/web-core/ui/stepper/ui-stepper.story.vue': {
      routes: '/story/web-core/ui/stepper/ui-stepper'
      views: never
    }
    'src/stories/web-core/ui/subtitle/ui-subtitle.story.vue': {
      routes: '/story/web-core/ui/subtitle/ui-subtitle'
      views: never
    }
    'src/stories/web-core/ui/table-actions/ui-table-actions.story.vue': {
      routes: '/story/web-core/ui/table-actions/ui-table-actions'
      views: never
    }
    'src/stories/web-core/ui/table-pagination/ui-table-pagination.story.vue': {
      routes: '/story/web-core/ui/table-pagination/ui-table-pagination'
      views: never
    }
    'src/stories/web-core/ui/tag/ui-tag.story.vue': {
      routes: '/story/web-core/ui/tag/ui-tag'
      views: never
    }
    'src/stories/web-core/ui/tag/ui-tags-list.story.vue': {
      routes: '/story/web-core/ui/tag/ui-tags-list'
      views: never
    }
    'src/stories/web-core/ui/task-item/ui-task-item.story.vue': {
      routes: '/story/web-core/ui/task-item/ui-task-item'
      views: never
    }
    'src/stories/web-core/ui/task-list/ui-task-list.story.vue': {
      routes: '/story/web-core/ui/task-list/ui-task-list'
      views: never
    }
    'src/stories/web-core/ui/title/ui-title.story.vue': {
      routes: '/story/web-core/ui/title/ui-title'
      views: never
    }
    'src/stories/web-core/ui/toaster/ui-toaster.story.vue': {
      routes: '/story/web-core/ui/toaster/ui-toaster'
      views: never
    }
    'src/stories/web-core/ui/toggle/ui-toggle.story.vue': {
      routes: '/story/web-core/ui/toggle/ui-toggle'
      views: never
    }
    'src/stories/web-core/ui/top-bottom-table/ui-top-bottom-table.story.vue': {
      routes: '/story/web-core/ui/top-bottom-table/ui-top-bottom-table'
      views: never
    }
    'src/stories/web-core/ui/tree-item-label/ui-tree-item-label.story.vue': {
      routes: '/story/web-core/ui/tree-item-label/ui-tree-item-label'
      views: never
    }
    'src/stories/web-core/ui/user-link/ui-user-link.story.vue': {
      routes: '/story/web-core/ui/user-link/ui-user-link'
      views: never
    }
    'src/stories/web-core/ui/user-logo/user-logo.story.vue': {
      routes: '/story/web-core/ui/user-logo/user-logo'
      views: never
    }
    'src/pages/vm/[uuid].vue': {
      routes:
        | '/vm/[uuid]'
        | '/vm/[uuid]/alarms'
        | '/vm/[uuid]/console'
        | '/vm/[uuid]/dashboard'
        | '/vm/[uuid]/network'
        | '/vm/[uuid]/stats'
        | '/vm/[uuid]/storage'
        | '/vm/[uuid]/system'
        | '/vm/[uuid]/tasks'
      views: 'default'
    }
    'src/pages/vm/[uuid]/alarms.vue': {
      routes: '/vm/[uuid]/alarms'
      views: never
    }
    'src/pages/vm/[uuid]/console.vue': {
      routes: '/vm/[uuid]/console'
      views: never
    }
    'src/pages/vm/[uuid]/dashboard.vue': {
      routes: '/vm/[uuid]/dashboard'
      views: never
    }
    'src/pages/vm/[uuid]/network.vue': {
      routes: '/vm/[uuid]/network'
      views: never
    }
    'src/pages/vm/[uuid]/stats.vue': {
      routes: '/vm/[uuid]/stats'
      views: never
    }
    'src/pages/vm/[uuid]/storage.vue': {
      routes: '/vm/[uuid]/storage'
      views: never
    }
    'src/pages/vm/[uuid]/system.vue': {
      routes: '/vm/[uuid]/system'
      views: never
    }
    'src/pages/vm/[uuid]/tasks.vue': {
      routes: '/vm/[uuid]/tasks'
      views: never
    }
    'src/pages/vm/new.vue': {
      routes: '/vm/new'
      views: never
    }
    'src/pages/xoa-deploy.vue': {
      routes: '/xoa-deploy'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info> ? Info['routes'] : keyof RouteNamedMap
}

export {}
