#!/bin/sh

set -eu

# compute the list of staged files we are interrested in
set --
buf=$(mktemp -u)
git diff-index --cached --diff-filter=AM --name-only HEAD > "$buf"
while IFS= read -r file
do
  case "$file" in
    *.js)
      set -- "$@" "$file";;
  esac
done < "$buf"

if [ $# -eq 0 ]
then
  exit
fi

eslint --fix "$@"

# stash unstaged changes
if stash=$(git stash create --keep-index --quiet)
then
  # unstash on exit
  trap 'git checkout $stash "$@"' EXIT
fi

#  run commands
eslint --fix "$@"
jest --findRelatedTests --passWithNoTests "$@"

# add any changes made by the commands
git add "$@"
