#!/usr/bin/env node

const { getPackages, writeFile, unlink } = require('./utils')

require('exec-promise')(() =>
  getPackages(true).map(({ dir, name, package: pkg }) => {
    pkg.name = name
    pkg.homepage = `https://github.com/vatesfr/xen-orchestra/tree/master/packages/${name}`
    pkg.bugs = `https://github.com/vatesfr/xo-web/issues`
    pkg.repository = {
      type: 'git',
      url: 'https://github.com/vatesfr/xen-orchestra.git'
    }

    const { devDependencies } = pkg
    if (devDependencies !== undefined) {
      delete devDependencies.ghooks
      delete devDependencies.husky
    }

    return Promise.all([
      writeFile(
        `${dir}/package.json`,
        JSON.stringify(pkg, null, 2) + '\n'
      ),
      unlink(`${dir}/.editorconfig`),
      unlink(`${dir}/.gitignore`),
      unlink(`${dir}/.jshintrc`),
      unlink(`${dir}/yarn.lock`)
    ])
  })
)
