//
// This file has been generated by [index-modules](https://npmjs.com/index-modules)
//

'use strict'

const d = Object.defineProperty
function de(o, n, v) {
  d(o, n, { enumerable: true, value: v })
  return v
}
function dl(o, n, g, a) {
  d(o, n, {
    configurable: true,
    enumerable: true,
    get: function () {
      return de(o, n, g(a))
    },
  })
}
function r(p) {
  const v = require(p)
  return v && v.__esModule
    ? v
    : typeof v === 'object' || typeof v === 'function'
    ? Object.create(v, { default: { enumerable: true, value: v } })
    : { default: v }
}
function e(p, i) {
  dl(defaults, i, function () {
    return exports[i].default
  })
  dl(exports, i, r, p)
}

d(exports, '__esModule', { value: true })
const defaults = de(exports, 'default', {})
e('./check.js', 'check')
e('./compare.js', 'compare')
e('./copy.js', 'copy')
e('./info.js', 'info')
e('./merge.js', 'merge')
e('./raw.js', 'raw')
e('./repl.js', 'repl')
e('./synthetize.js', 'synthetize')
