import { defineIconPack, type IconSingleConfig } from '@core/packages/icon'
import { faCopy, faSquare as checkboxEmpty, type IconDefinition } from '@fortawesome/free-regular-svg-icons'
import {
  faAdd,
  faArrowCircleRight,
  faArrowRight,
  faArrowRotateLeft,
  faArrowRotateRight,
  faArrowUpRightFromSquare,
  faBan,
  faBars,
  faBolt,
  faCamera,
  faCircle,
  faClone,
  faClose,
  faDownload,
  faEdit,
  faEllipsis,
  faEraser,
  faFillDrip,
  faHeart,
  faLightbulb,
  faLink,
  faLinkSlash,
  faMinus,
  faPowerOff,
  faRefresh,
  faRoute,
  faSearch,
  faSquare,
  faThumbTack,
  faThumbTackSlash,
  faTrash,
  faUpDown,
  faUpRightAndDownLeftFromCenter,
} from '@fortawesome/free-solid-svg-icons'

function constructIcon(icon: IconDefinition): IconSingleConfig {
  return {
    icon,
    color: 'var(--color-neutral-txt-primary)',
  }
}

export const actionIcons = defineIconPack({
  menu: constructIcon(faBars),
  'pin-panel': constructIcon(faThumbTack),
  'pin-panel-hide': constructIcon(faThumbTackSlash),
  resize: [
    {
      icon: faUpDown,
      color: 'var(--color-neutral-txt-primary)',
      rotate: 90,
    },
    {
      icon: faMinus,
      color: 'var(--color-neutral-txt-primary)',
      rotate: 90,
    },
  ],
  search: constructIcon(faSearch),
  'close-cancel-clear': constructIcon(faClose),
  disable: constructIcon(faBan),
  'disable-and-evacuate': [
    constructIcon(faBan),
    {
      icon: faCircle,
      color: 'var(--color-neutral-background-primary)',
      translate: [7, 5.5],
      size: 13,
    },
    {
      icon: faCircle,
      color: 'var(--color-neutral-txt-primary)',
      translate: [7, 5.5],
      size: 10,
    },
    {
      icon: faArrowRight,
      color: 'var(--color-neutral-background-primary)',
      translate: [7, 5.5],
      size: 6,
    },
  ],
  add: constructIcon(faAdd),
  'add-circle': [
    {
      icon: faCircle,
      color: 'var(--color-brand-item-base)',
    },
    {
      icon: faAdd,
      color: 'var(--color-brand-txt-item)',
      size: 10,
    },
  ],
  remove: constructIcon(faMinus),
  force: constructIcon(faBolt),
  smart: constructIcon(faLightbulb),
  'open-in-new-tab': constructIcon(faArrowUpRightFromSquare),
  'open-fullscreen': constructIcon(faUpRightAndDownLeftFromCenter),
  screenshot: [
    // faDrawSquare is pro version
    constructIcon(checkboxEmpty),
    {
      icon: faCircle,
      color: 'var(--color-neutral-txt-primary)',
      size: 4,
      translate: [6, 6],
    },
    {
      icon: faCircle,
      color: 'var(--color-neutral-txt-primary)',
      size: 4,
      translate: [-6, -6],
    },
    {
      icon: faCircle,
      color: 'var(--color-neutral-txt-primary)',
      size: 4,
      translate: [6, -6],
    },
    {
      icon: faCircle,
      color: 'var(--color-neutral-txt-primary)',
      size: 4,
      translate: [-6, 6],
    },
  ],
  edit: constructIcon(faEdit),
  fill: constructIcon(faFillDrip),
  duplicate: constructIcon(faClone),
  copy: constructIcon(faCopy),
  connect: constructIcon(faLink),
  disconnect: constructIcon(faLinkSlash),
  forget: constructIcon(faEraser),
  delete: { icon: faTrash, color: 'var(--color-danger-txt-primary)' },
  'more-actions': constructIcon(faEllipsis),
  'more-actions-vertical': {
    icon: faEllipsis,
    color: 'var(--color-neutral-txt-primary)',
    rotate: 90,
  },
  reboot: constructIcon(faArrowRotateRight),
  'force-reboot': [
    constructIcon(faArrowRotateRight),
    {
      icon: faCircle,
      color: 'var(--color-neutral-background-primary)',
      translate: [7, 5.5],
      size: 13,
    },
    {
      icon: faCircle,
      color: 'var(--color-neutral-txt-primary)',
      translate: [7, 5.5],
      size: 10,
    },
    {
      icon: faBolt,
      color: 'var(--color-neutral-background-primary)',
      translate: [7, 5.5],
      size: 6,
    },
  ],
  shutdown: constructIcon(faSquare),
  'force-shutdown': [
    constructIcon(faSquare),
    {
      icon: faCircle,
      color: 'var(--color-neutral-background-primary)',
      translate: [7, 5.5],
      size: 13,
    },
    {
      icon: faCircle,
      color: 'var(--color-neutral-txt-primary)',
      translate: [7, 5.5],
      size: 10,
    },
    {
      icon: faBolt,
      color: 'var(--color-neutral-background-primary)',
      translate: [7, 5.5],
      size: 6,
    },
  ],
  'smart-reboot': [
    constructIcon(faArrowRotateRight),
    {
      icon: faCircle,
      color: 'var(--color-neutral-background-primary)',
      translate: [7, 5.5],
      size: 13,
    },
    {
      icon: faLightbulb,
      color: 'var(--color-neutral-txt-primary)',
      translate: [7, 5.5],
      size: 10,
    },
  ],
  undo: constructIcon(faArrowRotateLeft),
  scan: constructIcon(faRefresh),
  'change-state': constructIcon(faPowerOff),
  migrate: constructIcon(faRoute),
  snapshot: constructIcon(faCamera),
  download: constructIcon(faDownload),
  'health-check': constructIcon(faHeart),
  evacuate: constructIcon(faArrowCircleRight),
})
