import { defineIconPack } from '@core/packages/icon/define-icon-pack.ts'
import { faBuilding, faFile, faFolderClosed, faFolderOpen, faSquareCheck } from '@fortawesome/free-regular-svg-icons'
import {
  faAlignLeft,
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAngleUp,
  faArrowDown,
  faArrowRight,
  faArrowRightFromBracket,
  faArrowUp,
  faArrowUpRightFromSquare,
  faAt,
  faBars,
  faBarsProgress,
  faBook,
  faCamera,
  faCaretDown,
  faCaretUp,
  faCheck,
  faCircle,
  faCircleCheck,
  faCircleMinus,
  faCircleNotch,
  faCirclePlay,
  faCircleXmark,
  faCity,
  faClose,
  faCode,
  faComments,
  faCopy,
  faDatabase,
  faDesktop,
  faDisplay,
  faDownLeftAndUpRightToCenter,
  faDownload,
  faEarthAmericas,
  faEdit,
  faEllipsis,
  faEllipsisVertical,
  faExternalLink,
  faEyeSlash,
  faFileCsv,
  faFileExport,
  faFilter,
  faFont,
  faGear,
  faHashtag,
  faHeadset,
  faKeyboard,
  faLayerGroup,
  faList,
  faLock,
  faLockOpen,
  faMagnifyingGlass,
  faMemory,
  faMicrochip,
  faMinus,
  faMoon,
  faNetworkWired,
  faPause,
  faPencil,
  faPlay,
  faPlug,
  faPlus,
  faPowerOff,
  faRemove,
  faRepeat,
  faRotateLeft,
  faRoute,
  faSatellite,
  faServer,
  faSliders,
  faTrash,
  faUpRightAndDownLeftFromCenter,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'

export const faIcons = defineIconPack({
  'align-left': { icon: faAlignLeft },
  'angle-double-left': { icon: faAngleDoubleLeft },
  'angle-double-right': { icon: faAngleDoubleRight },
  'angle-down': { icon: faAngleDown },
  'angle-left': { icon: faAngleLeft },
  'angle-right': { icon: faAngleRight },
  'angle-up': { icon: faAngleUp },
  'arrow-down': { icon: faArrowDown },
  'arrow-right': { icon: faArrowRight },
  'arrow-right-from-bracket': { icon: faArrowRightFromBracket },
  'arrow-up': { icon: faArrowUp },
  'arrow-up-right-from-square': { icon: faArrowUpRightFromSquare },
  at: { icon: faAt },
  bars: { icon: faBars },
  'bars-progress': { icon: faBarsProgress },
  book: { icon: faBook },
  building: { icon: faBuilding },
  camera: { icon: faCamera },
  'caret-down': { icon: faCaretDown },
  'caret-up': { icon: faCaretUp },
  check: { icon: faCheck },
  circle: { icon: faCircle },
  'circle-check': { icon: faCircleCheck },
  'circle-minus': { icon: faCircleMinus },
  'circle-notch': { icon: faCircleNotch },
  'circle-play': { icon: faCirclePlay },
  'circle-xmark': { icon: faCircleXmark },
  city: { icon: faCity },
  close: { icon: faClose },
  code: { icon: faCode },
  comments: { icon: faComments },
  copy: { icon: faCopy },
  database: { icon: faDatabase },
  desktop: { icon: faDesktop },
  display: { icon: faDisplay },
  'down-left-and-up-right-to-center': { icon: faDownLeftAndUpRightToCenter },
  download: { icon: faDownload },
  'earth-americas': { icon: faEarthAmericas },
  edit: { icon: faEdit },
  ellipsis: { icon: faEllipsis },
  'ellipsis-vertical': { icon: faEllipsisVertical },
  'external-link': { icon: faExternalLink },
  'eye-slash': { icon: faEyeSlash },
  file: { icon: faFile },
  'file-csv': { icon: faFileCsv },
  'file-export': { icon: faFileExport },
  filter: { icon: faFilter },
  'folder-closed': { icon: faFolderClosed },
  'folder-open': { icon: faFolderOpen },
  font: { icon: faFont },
  gear: { icon: faGear },
  hashtag: { icon: faHashtag },
  headset: { icon: faHeadset },
  keyboard: { icon: faKeyboard },
  'layer-group': { icon: faLayerGroup },
  list: { icon: faList },
  lock: { icon: faLock },
  'lock-open': { icon: faLockOpen },
  'magnifying-glass': { icon: faMagnifyingGlass },
  memory: { icon: faMemory },
  microchip: { icon: faMicrochip },
  minus: { icon: faMinus },
  moon: { icon: faMoon },
  'network-wired': { icon: faNetworkWired },
  pause: { icon: faPause },
  pencil: { icon: faPencil },
  play: { icon: faPlay },
  plug: { icon: faPlug },
  plus: { icon: faPlus },
  'power-off': { icon: faPowerOff },
  remove: { icon: faRemove },
  repeat: { icon: faRepeat },
  'rotate-left': { icon: faRotateLeft },
  route: { icon: faRoute },
  satellite: { icon: faSatellite },
  server: { icon: faServer },
  sliders: { icon: faSliders },
  'square-check': { icon: faSquareCheck },
  trash: { icon: faTrash },
  'up-right-and-down-left-from-center': { icon: faUpRightAndDownLeftFromCenter },
  xmark: { icon: faXmark },
})
