export XoHighLevelObjectInput from './xo-highlevel-object-input'
export XoHostInput from './xo-host-input'
export XoPoolInput from './xo-pool-input'
export XoRemoteInput from './xo-remote-input'
export XoRoleInput from './xo-role-input'
export XoSrInput from './xo-sr-input'
export XoSubjectInput from './xo-subject-input'
export XoVmInput from './xo-vm-input'
