#!/usr/bin/env node

var join = require('path').join
var writeFile = require('fs').writeFileSync

// ===================================================================

function mapIn (object, iteratee) {
  var result = []
  for (var key in object) {
    result.push(iteratee(object[key], key, object))
  }
  return result
}

// ===================================================================

var messages = require('../src/common/intl/messages')
var lang = process.argv[2]

var content = [
  '// See http://momentjs.com/docs/#/use-it/browserify/',
  'import \'moment/locale/' + lang + '\'',
  '',
  'import reactIntlData from \'react-intl/locale-data/' + lang + '\'',
  'import { addLocaleData } from \'react-intl\'',
  'addLocaleData(reactIntlData)',
  '',
  '// ===================================================================',
  '',
  'export default {'
]

content.push(mapIn(messages, function (message, id) {
  return [
    '  // Original text: ', JSON.stringify(message.defaultMessage, null), '\n',
    '  ', id, ': undefined'
  ].join('')
}).join(',\n\n'))

content.push('}', '')

writeFile(
  join(__dirname, '../src/common/intl/locales/', lang + '.js'),
  content.join('\n'),
  {
    flag: 'wx'
  }
)
