import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

/*
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
};

*/

export default {
  docs: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Getting started',
      collapsible: true,
      collapsed: false,
      items: [
        'releases',
        'supported_hosts',
        'installation',
        'configuration',
        'updater',
        'migrate_to_new_xoa',
        'architecture',
        'troubleshooting',
        'install-from-sources',
      ],
    },
    {
      type: 'category',
      label: 'Using Xen Orchestra',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'XO 6',
          collapsible: true,
          collapsed: false,
          items: [
            'xo6/whatsnew',
            'xo6/xo6vsxo5',
            'xo6/gettingstarted',
            'xo6/coreconcepts',
            'xo6/management',
            'xo6/backups',
          ],
        },
        {
          type: 'category',
          label: 'XO 5',
          collapsible: true,
          collapsed: true,
          items: [
            'xo5/manage',
            'xo5/manage_infrastructure',
            'xo5/users',
            'xo5/vm-templates',
            'windows-templates',
            'xo5/advanced',
            'xo5/load_balancing',
            'xo5/sdn_controller',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Backups and DR',
      collapsible: true,
      collapsed: true,
      items: [
        'xo5/intro_backup',
        'xo5/backups',
        'xo5/backup_howto',
        'xo5/proxy',
        'distributed_backups',
        'xo5/rolling_snapshots',
        'xo5/full_backups',
        'xo5/incremental_backups',
        'xo5/full_replication',
        'xo5/incremental_replication',
        'xo5/mirror_backup',
        'xo5/metadata_backup',
        'xo5/immutability',
        'xo5/backup_reports',
        'xo5/backup_troubleshooting',
        'xo5/calculator',
      ],
    },
    {
      type: 'category',
      label: 'Migrating to XO',
      collapsible: true,
      collapsed: true,
      items: ['xo5/v2v-migration-guide', 'xo5/object-storage-support'],
    },
    {
      type: 'category',
      label: 'Automation',
      collapsible: true,
      collapsed: true,
      items: [
        'xo5/restapi',
        'xo5/mcp',
        'xo6/terraform-provider',
        'xo6/ansible',
        'xo6/pulumi-provider',
        'xo6/packer-provider',
        'xo6/powershell-module',
        'xo6/kubernetes',
      ],
    },
    {
      type: 'category',
      label: 'Security',
      collapsible: true,
      collapsed: true,
      items: ['xo5/credential-encryption', 'xo6/acl-v2'],
    },
    {
      type: 'category',
      label: 'Support and licensing',
      collapsible: true,
      collapsed: true,
      items: ['xo6/intro_support', 'xo6/purchase', 'xo6/community', 'xo5/xoa', 'xo5/license_management'],
    },
    {
      type: 'category',
      label: 'Project',
      collapsible: true,
      collapsed: true,
      items: [
        'intro_project',
        {
          type: 'link',
          label: 'Blog',
          href: 'https://xen-orchestra.com/blog/',
        },
        {
          type: 'link',
          label: 'Changelog',
          href: 'https://github.com/vatesfr/xen-orchestra/blob/master/CHANGELOG.md#changelog',
        },
        'contributing',
        'licenses',
        {
          type: 'link',
          label: 'Roadmap',
          href: 'https://docs.vates.tech/product-roadmap/',
        },
        'glossary',
      ],
    },
  ],
}

//export default sidebars;
