import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

/*
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
};

*/

export default {
  docs: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Getting started',
      collapsible: true,
      collapsed: false,
      items: [
        'releases',
        'supported_hosts',
        'installation',
        'install-from-sources',
        'configuration',
        'updater',
        'migrate_to_new_xoa',
        'troubleshooting',
        'architecture',
      ],
    },
    {
      type: 'category',
      label: 'Discover Xen Orchestra',
      collapsible: true,
      collapsed: false,
      items: ['xo6/whatsnew', 'xo6/xo6vsxo5', 'xo6/gettingstarted', 'xo6/coreconcepts'],
    },
    {
      type: 'category',
      label: 'Manage your infrastructure',
      collapsible: true,
      collapsed: true,
      items: [
        'xo6/management',
        'xo5/manage_infrastructure',
        'xo5/vm-templates',
        'xo5/advanced',
        'xo5/load_balancing',
        'xo5/sdn_controller',
        'xo5/ipmi-plugin',
      ],
    },
    {
      type: 'category',
      label: 'Backups and DR',
      collapsible: true,
      collapsed: true,
      items: [
        'intro_backup',
        'backup_howto',
        'xo6/backups',
        {
          type: 'category',
          label: 'Backup types',
          collapsible: true,
          collapsed: true,
          items: [
            'rolling_snapshots',
            'full_backups',
            'xo5/incremental_backups',
            'full_replication',
            'xo5/incremental_replication',
            'mirror_backup',
            'xo5/metadata_backup',
          ],
        },
        'xo5/backups',
        {
          type: 'category',
          label: 'Scale and security',
          collapsible: true,
          collapsed: true,
          items: ['xo5/proxy', 'distributed_backups', 'object-storage-support', 'immutability'],
        },
        'xo5/backup_reports',
        'xo5/backup_troubleshooting',
        'calculator',
      ],
    },
    {
      type: 'category',
      label: 'Users and access',
      collapsible: true,
      collapsed: true,
      items: ['xo5/users', 'rbac', 'credential-encryption'],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsible: true,
      collapsed: true,
      items: ['xo5/v2v-migration-guide', 'windows-templates'],
    },
    {
      type: 'category',
      label: 'Automation',
      collapsible: true,
      collapsed: true,
      items: [
        'automation/restapi',
        'automation/mcp',
        'automation/terraform-provider',
        'automation/ansible',
        'automation/pulumi-provider',
        'automation/packer-provider',
        'automation/powershell-module',
        'automation/kubernetes',
      ],
    },
    {
      type: 'category',
      label: 'Support and licensing',
      collapsible: true,
      collapsed: true,
      items: [
        'intro_support',
        {
          type: 'link',
          label: 'Vates VMS bundles',
          href: 'https://docs.vates.tech/pricing-licencing/vms-bundle-overview/',
        },
        {
          type: 'link',
          label: 'Applying XO licenses',
          href: 'https://docs.vates.tech/pricing-licencing/applying-xo-licences/',
        },
        'community',
      ],
    },
    {
      type: 'category',
      label: 'Project',
      collapsible: true,
      collapsed: true,
      items: [
        'intro_project',
        {
          type: 'link',
          label: 'Blog',
          href: 'https://xen-orchestra.com/blog/',
        },
        {
          type: 'link',
          label: 'Changelog',
          href: 'https://github.com/vatesfr/xen-orchestra/blob/master/CHANGELOG.md#changelog',
        },
        'contributing',
        'licenses',
        {
          type: 'link',
          label: 'Roadmap',
          href: 'https://docs.vates.tech/product-roadmap/',
        },
        'glossary',
      ],
    },
  ],
}

//export default sidebars;
