import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

/*
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
};

*/

export default {
  docs: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Xen Orchestra',
      collapsible: true,
      collapsed: true,
      items: [
        'releases',
        'supported_hosts',
        'installation',
        'configuration',
        'migrate_to_new_xoa',
        'updater',
        'architecture',
        'troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Management',
      collapsible: true,
      collapsed: true,
      items: [
        'manage',
        'manage_infrastructure',
        'users',
        'advanced',
        'load_balancing',
        'sdn_controller',
        'restapi',
        'xosan',
        'xosanv2',
      ],
    },
     {
      type: 'category',
      label: 'Backups',
      collapsible: true,
      collapsed: true,
      items: [
        'intro_backup',
        'backups',
        'proxy',
        'rolling_snapshots',
        'full_backups',
        'delta_backups',
        'disaster_recovery',
        'continuous_replication',
        'mirror_backup',
        'metadata_backup',
        'backup_reports',
        'backup_troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Support',
      collapsible: true,
      collapsed: true,
      items: [
        'intro_support',
        'xoa',
        'purchase',
        'license_management',
        'community',
      ],
    },
    {
      type: 'category',
      label: 'Project',
      collapsible: true,
      collapsed: true,
      items: [
        'intro_project',
        {
          type: 'link',
          label: 'Changelog',
          href: 'https://github.com/vatesfr/xen-orchestra/blob/master/CHANGELOG.md#changelog',
        },
        'code_of_conduct',
        'contributing',
        'licenses',
        'roadmap',
        'glossary',
      ],
    },
  ],
};

//export default sidebars;
