/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(site)': RouteRecordInfo<
      '/(site)',
      '/',
      Record<never, never>,
      Record<never, never>,
      '/(site)/backups' | '/(site)/dashboard' | '/(site)/hosts' | '/(site)/pools' | '/(site)/tasks' | '/(site)/vms'
    >
    '/(site)/backups': RouteRecordInfo<'/(site)/backups', '/backups', Record<never, never>, Record<never, never>, never>
    '/(site)/dashboard': RouteRecordInfo<
      '/(site)/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/(site)/hosts': RouteRecordInfo<'/(site)/hosts', '/hosts', Record<never, never>, Record<never, never>, never>
    '/(site)/pools': RouteRecordInfo<'/(site)/pools', '/pools', Record<never, never>, Record<never, never>, never>
    '/(site)/tasks': RouteRecordInfo<'/(site)/tasks', '/tasks', Record<never, never>, Record<never, never>, never>
    '/(site)/vms': RouteRecordInfo<'/(site)/vms', '/vms', Record<never, never>, Record<never, never>, never>
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      never
    >
    '/backup/[id]': RouteRecordInfo<
      '/backup/[id]',
      '/backup/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      '/backup/[id]/backed-up-vms' | '/backup/[id]/configuration' | '/backup/[id]/runs' | '/backup/[id]/targets'
    >
    '/backup/[id]/backed-up-vms': RouteRecordInfo<
      '/backup/[id]/backed-up-vms',
      '/backup/:id/backed-up-vms',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/backup/[id]/configuration': RouteRecordInfo<
      '/backup/[id]/configuration',
      '/backup/:id/configuration',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/backup/[id]/runs': RouteRecordInfo<
      '/backup/[id]/runs',
      '/backup/:id/runs',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/backup/[id]/targets': RouteRecordInfo<
      '/backup/[id]/targets',
      '/backup/:id/targets',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/dev/': RouteRecordInfo<'/dev/', '/dev', Record<never, never>, Record<never, never>, never>
    '/dev/colors': RouteRecordInfo<'/dev/colors', '/dev/colors', Record<never, never>, Record<never, never>, never>
    '/dev/icons/': RouteRecordInfo<'/dev/icons/', '/dev/icons', Record<never, never>, Record<never, never>, never>
    '/dev/icons/[name]': RouteRecordInfo<
      '/dev/icons/[name]',
      '/dev/icons/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      never
    >
    '/dev/token': RouteRecordInfo<'/dev/token', '/dev/token', Record<never, never>, Record<never, never>, never>
    '/host/[id]': RouteRecordInfo<
      '/host/[id]',
      '/host/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | '/host/[id]/console'
      | '/host/[id]/dashboard'
      | '/host/[id]/networks'
      | '/host/[id]/storage'
      | '/host/[id]/system'
      | '/host/[id]/tasks'
      | '/host/[id]/vms'
    >
    '/host/[id]/console': RouteRecordInfo<
      '/host/[id]/console',
      '/host/:id/console',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/host/[id]/dashboard': RouteRecordInfo<
      '/host/[id]/dashboard',
      '/host/:id/dashboard',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/host/[id]/networks': RouteRecordInfo<
      '/host/[id]/networks',
      '/host/:id/networks',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/host/[id]/storage': RouteRecordInfo<
      '/host/[id]/storage',
      '/host/:id/storage',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/host/[id]/system': RouteRecordInfo<
      '/host/[id]/system',
      '/host/:id/system',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/host/[id]/tasks': RouteRecordInfo<
      '/host/[id]/tasks',
      '/host/:id/tasks',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/host/[id]/vms': RouteRecordInfo<
      '/host/[id]/vms',
      '/host/:id/vms',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/pool/[id]': RouteRecordInfo<
      '/pool/[id]',
      '/pool/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | '/pool/[id]/dashboard'
      | '/pool/[id]/hosts'
      | '/pool/[id]/networks'
      | '/pool/[id]/storage'
      | '/pool/[id]/system'
      | '/pool/[id]/tasks'
      | '/pool/[id]/vms'
    >
    '/pool/[id]/dashboard': RouteRecordInfo<
      '/pool/[id]/dashboard',
      '/pool/:id/dashboard',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/pool/[id]/hosts': RouteRecordInfo<
      '/pool/[id]/hosts',
      '/pool/:id/hosts',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/pool/[id]/networks': RouteRecordInfo<
      '/pool/[id]/networks',
      '/pool/:id/networks',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/pool/[id]/storage': RouteRecordInfo<
      '/pool/[id]/storage',
      '/pool/:id/storage',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/pool/[id]/system': RouteRecordInfo<
      '/pool/[id]/system',
      '/pool/:id/system',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/pool/[id]/tasks': RouteRecordInfo<
      '/pool/[id]/tasks',
      '/pool/:id/tasks',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/pool/[id]/vms': RouteRecordInfo<
      '/pool/[id]/vms',
      '/pool/:id/vms',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/pool/connect': RouteRecordInfo<
      '/pool/connect',
      '/pool/connect',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>, never>
    '/vm/[id]': RouteRecordInfo<
      '/vm/[id]',
      '/vm/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | '/vm/[id]/backups'
      | '/vm/[id]/console'
      | '/vm/[id]/dashboard'
      | '/vm/[id]/networks'
      | '/vm/[id]/snapshots'
      | '/vm/[id]/system'
      | '/vm/[id]/tasks'
      | '/vm/[id]/vdis'
    >
    '/vm/[id]/backups': RouteRecordInfo<
      '/vm/[id]/backups',
      '/vm/:id/backups',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/vm/[id]/console': RouteRecordInfo<
      '/vm/[id]/console',
      '/vm/:id/console',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/vm/[id]/dashboard': RouteRecordInfo<
      '/vm/[id]/dashboard',
      '/vm/:id/dashboard',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/vm/[id]/networks': RouteRecordInfo<
      '/vm/[id]/networks',
      '/vm/:id/networks',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/vm/[id]/snapshots': RouteRecordInfo<
      '/vm/[id]/snapshots',
      '/vm/:id/snapshots',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/vm/[id]/system': RouteRecordInfo<
      '/vm/[id]/system',
      '/vm/:id/system',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/vm/[id]/tasks': RouteRecordInfo<
      '/vm/[id]/tasks',
      '/vm/:id/tasks',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/vm/[id]/vdis': RouteRecordInfo<
      '/vm/[id]/vdis',
      '/vm/:id/vdis',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/vm/new': RouteRecordInfo<'/vm/new', '/vm/new', Record<never, never>, Record<never, never>, never>
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(site).vue': {
      routes:
        | '/(site)'
        | '/(site)/backups'
        | '/(site)/dashboard'
        | '/(site)/hosts'
        | '/(site)/pools'
        | '/(site)/tasks'
        | '/(site)/vms'
      views: 'default'
    }
    'src/pages/(site)/backups.vue': {
      routes: '/(site)/backups'
      views: never
    }
    'src/pages/(site)/dashboard.vue': {
      routes: '/(site)/dashboard'
      views: never
    }
    'src/pages/(site)/hosts.vue': {
      routes: '/(site)/hosts'
      views: never
    }
    'src/pages/(site)/pools.vue': {
      routes: '/(site)/pools'
      views: never
    }
    'src/pages/(site)/tasks.vue': {
      routes: '/(site)/tasks'
      views: never
    }
    'src/pages/(site)/vms.vue': {
      routes: '/(site)/vms'
      views: never
    }
    'src/pages/[...path].vue': {
      routes: '/[...path]'
      views: never
    }
    'src/pages/backup/[id].vue': {
      routes:
        | '/backup/[id]'
        | '/backup/[id]/backed-up-vms'
        | '/backup/[id]/configuration'
        | '/backup/[id]/runs'
        | '/backup/[id]/targets'
      views: 'default'
    }
    'src/pages/backup/[id]/backed-up-vms.vue': {
      routes: '/backup/[id]/backed-up-vms'
      views: never
    }
    'src/pages/backup/[id]/configuration.vue': {
      routes: '/backup/[id]/configuration'
      views: never
    }
    'src/pages/backup/[id]/runs.vue': {
      routes: '/backup/[id]/runs'
      views: never
    }
    'src/pages/backup/[id]/targets.vue': {
      routes: '/backup/[id]/targets'
      views: never
    }
    'src/pages/dev/index.vue': {
      routes: '/dev/'
      views: never
    }
    'src/pages/dev/colors.vue': {
      routes: '/dev/colors'
      views: never
    }
    'src/pages/dev/icons/index.vue': {
      routes: '/dev/icons/'
      views: never
    }
    'src/pages/dev/icons/[name].vue': {
      routes: '/dev/icons/[name]'
      views: never
    }
    'src/pages/dev/token.vue': {
      routes: '/dev/token'
      views: never
    }
    'src/pages/host/[id].vue': {
      routes:
        | '/host/[id]'
        | '/host/[id]/console'
        | '/host/[id]/dashboard'
        | '/host/[id]/networks'
        | '/host/[id]/storage'
        | '/host/[id]/system'
        | '/host/[id]/tasks'
        | '/host/[id]/vms'
      views: 'default'
    }
    'src/pages/host/[id]/console.vue': {
      routes: '/host/[id]/console'
      views: never
    }
    'src/pages/host/[id]/dashboard.vue': {
      routes: '/host/[id]/dashboard'
      views: never
    }
    'src/pages/host/[id]/networks.vue': {
      routes: '/host/[id]/networks'
      views: never
    }
    'src/pages/host/[id]/storage.vue': {
      routes: '/host/[id]/storage'
      views: never
    }
    'src/pages/host/[id]/system.vue': {
      routes: '/host/[id]/system'
      views: never
    }
    'src/pages/host/[id]/tasks.vue': {
      routes: '/host/[id]/tasks'
      views: never
    }
    'src/pages/host/[id]/vms.vue': {
      routes: '/host/[id]/vms'
      views: never
    }
    'src/pages/pool/[id].vue': {
      routes:
        | '/pool/[id]'
        | '/pool/[id]/dashboard'
        | '/pool/[id]/hosts'
        | '/pool/[id]/networks'
        | '/pool/[id]/storage'
        | '/pool/[id]/system'
        | '/pool/[id]/tasks'
        | '/pool/[id]/vms'
      views: 'default'
    }
    'src/pages/pool/[id]/dashboard.vue': {
      routes: '/pool/[id]/dashboard'
      views: never
    }
    'src/pages/pool/[id]/hosts.vue': {
      routes: '/pool/[id]/hosts'
      views: never
    }
    'src/pages/pool/[id]/networks.vue': {
      routes: '/pool/[id]/networks'
      views: never
    }
    'src/pages/pool/[id]/storage.vue': {
      routes: '/pool/[id]/storage'
      views: never
    }
    'src/pages/pool/[id]/system.vue': {
      routes: '/pool/[id]/system'
      views: never
    }
    'src/pages/pool/[id]/tasks.vue': {
      routes: '/pool/[id]/tasks'
      views: never
    }
    'src/pages/pool/[id]/vms.vue': {
      routes: '/pool/[id]/vms'
      views: never
    }
    'src/pages/pool/connect.vue': {
      routes: '/pool/connect'
      views: never
    }
    'src/pages/settings.vue': {
      routes: '/settings'
      views: never
    }
    'src/pages/vm/[id].vue': {
      routes:
        | '/vm/[id]'
        | '/vm/[id]/backups'
        | '/vm/[id]/console'
        | '/vm/[id]/dashboard'
        | '/vm/[id]/networks'
        | '/vm/[id]/snapshots'
        | '/vm/[id]/system'
        | '/vm/[id]/tasks'
        | '/vm/[id]/vdis'
      views: 'default'
    }
    'src/pages/vm/[id]/backups.vue': {
      routes: '/vm/[id]/backups'
      views: never
    }
    'src/pages/vm/[id]/console.vue': {
      routes: '/vm/[id]/console'
      views: never
    }
    'src/pages/vm/[id]/dashboard.vue': {
      routes: '/vm/[id]/dashboard'
      views: never
    }
    'src/pages/vm/[id]/networks.vue': {
      routes: '/vm/[id]/networks'
      views: never
    }
    'src/pages/vm/[id]/snapshots.vue': {
      routes: '/vm/[id]/snapshots'
      views: never
    }
    'src/pages/vm/[id]/system.vue': {
      routes: '/vm/[id]/system'
      views: never
    }
    'src/pages/vm/[id]/tasks.vue': {
      routes: '/vm/[id]/tasks'
      views: never
    }
    'src/pages/vm/[id]/vdis.vue': {
      routes: '/vm/[id]/vdis'
      views: never
    }
    'src/pages/vm/new.vue': {
      routes: '/vm/new'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info> ? Info['routes'] : keyof RouteNamedMap
}

export {}
