export const vmSnapshotIds = [
  '/rest/v0/vm-snapshots/d68fca2c-41e6-be87-d790-105c1642a090',
  '/rest/v0/vm-snapshots/926ed61e-f8c9-8619-da05-1f454ed3dec9',
]

export const partialVmSnapshots = [
  {
    uuid: '926ed61e-f8c9-8619-da05-1f454ed3dec9',
    snapshot_time: 1726489407,
    $snapshot_of: '4127cb83-5a72-21fb-29de-3c9823ea5f43',
    href: '/rest/v0/vm-snapshots/926ed61e-f8c9-8619-da05-1f454ed3dec9',
  },
  {
    uuid: '063ff4d6-f3b2-cf64-42b5-ae2cc51c1643',
    snapshot_time: 1732707379,
    $snapshot_of: 'fa8e50dd-68d6-3233-a580-96d1e8103cdd',
    href: '/rest/v0/vm-snapshots/063ff4d6-f3b2-cf64-42b5-ae2cc51c1643',
  },
]

export const vmSnapshot = {
  $pool: 'string',
  _xapiRef: 'string',
  uuid: 'string',
  $VBDs: ['string'],
  $VGPUs: ['string'],
  $container: 'string',
  CPUs: {
    number: 0,
    max: 0,
  },
  PV_args: 'string',
  VGPUs: ['string'],
  VIFs: ['string'],
  VTPMs: ['string'],
  addresses: {
    additionalProp1: 'string',
    additionalProp2: 'string',
    additionalProp3: 'string',
  },
  affinityHost: 'string',
  attachedPcis: ['string'],
  auto_poweron: true,
  bios_strings: {
    additionalProp1: 'string',
    additionalProp2: 'string',
    additionalProp3: 'string',
  },
  blockedOperations: {
    destroy: 'string',
    provision: 'string',
    shutdown: 'string',
    assert_operation_valid: 'string',
    awaiting_memory_live: 'string',
    call_plugin: 'string',
    changing_dynamic_range: 'string',
    changing_memory_limits: 'string',
    changing_memory_live: 'string',
    changing_NVRAM: 'string',
    changing_shadow_memory: 'string',
    changing_shadow_memory_live: 'string',
    changing_static_range: 'string',
    changing_VCPUs: 'string',
    changing_VCPUs_live: 'string',
    checkpoint: 'string',
    clean_reboot: 'string',
    clean_shutdown: 'string',
    clone: 'string',
    copy: 'string',
    create_template: 'string',
    create_vtpm: 'string',
    csvm: 'string',
    data_source_op: 'string',
    export: 'string',
    get_boot_record: 'string',
    hard_reboot: 'string',
    hard_shutdown: 'string',
    import: 'string',
    make_into_template: 'string',
    metadata_export: 'string',
    migrate_send: 'string',
    pause: 'string',
    pool_migrate: 'string',
    power_state_reset: 'string',
    query_services: 'string',
    resume: 'string',
    resume_on: 'string',
    revert: 'string',
    reverting: 'string',
    send_sysrq: 'string',
    send_trigger: 'string',
    snapshot: 'string',
    snapshot_with_quiesce: 'string',
    start: 'string',
    start_on: 'string',
    suspend: 'string',
    unpause: 'string',
    update_allowed_operations: 'string',
  },
  boot: {
    additionalProp1: 'string',
    additionalProp2: 'string',
    additionalProp3: 'string',
  },
  coresPerSocket: 0,
  cpuCap: 0,
  cpuMask: [0],
  cpuWeight: 0,
  creation: {
    additionalProp1: 'string',
    additionalProp2: 'string',
    additionalProp3: 'string',
  },
  current_operations: {
    additionalProp1: 'destroy',
    additionalProp2: 'destroy',
    additionalProp3: 'destroy',
  },
  docker: {
    version: 'string',
    process: 'string',
    info: 'string',
    enabled: true,
    containers: ['string'],
  },
  expNestedHvm: true,
  hasVendorDevice: true,
  high_availability: 'string',
  installTime: 0,
  isFirmwareSupported: true,
  memory: {
    usage: 0,
    static: [0],
    size: 0,
    dynamic: [0],
  },
  mainIpAddress: 'string',
  managementAgentDetected: true,
  name_description: 'string',
  name_label: 'string',
  needsVtpm: true,
  nicType: 'string',
  notes: 'string',
  os_version: {
    additionalProp1: 'string',
    additionalProp2: 'string',
    additionalProp3: 'string',
  },
  other: {
    additionalProp1: 'string',
    additionalProp2: 'string',
    additionalProp3: 'string',
  },
  parent: 'string',
  power_state: 'Running',
  pvDriversDetected: true,
  pvDriversUpToDate: true,
  pvDriversVersion: 'string',
  resourceSet: 'string',
  secureBoot: true,
  snapshots: ['string'],
  startDelay: 0,
  startTime: 0,
  suspendSr: 'string',
  tags: ['string'],
  vga: 'string',
  videoram: 0,
  viridian: true,
  virtualizationMode: 'hvm',
  xenStoreData: {
    additionalProp1: 'string',
    additionalProp2: 'string',
    additionalProp3: 'string',
  },
  $snapshot_of: 'string',
  id: 'string',
  snapshot_time: 0,
  suspendVdi: 'string',
  type: 'VM-snapshot',
}
