name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build docker image
        run: docker-compose -f docker/docker-compose.dev.yml build
      - name: Create the container and start the tests
        run: docker-compose -f docker/docker-compose.dev.yml up --exit-code-from xo